/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({jsTree:{},reporteesEndpoint:'',currentTreeUrl:'',currentRootId:'',selectedUser:{},initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.reporteesEndpoint=app.api.serverUrl+"/Forecasts/reportees/";this.currentTreeUrl=this.reporteesEndpoint+app.user.get('id');this.currentRootId=app.user.get('id');this.selectedUser=app.user.toJSON();},render:function(){if(app.user.get('isManager')){app.view.View.prototype.render.call(this);}},unbindData:function(){if(this.context.forecasts)this.context.forecasts.off(null,null,this);app.view.View.prototype.unbindData.call(this);},bindDataChange:function(){if(this.context.forecasts){this.context.forecasts.on("change:selectedUser",this.checkRender,this);}},checkRender:function(context,selectedUser){this.selectedUser=selectedUser;if(selectedUser.showOpps){var nodeId=(selectedUser.isManager?'jstree_node_myopps_':'jstree_node_')+selectedUser.user_name;this.selectJSTreeNode(nodeId)}else if(this.currentRootId!=selectedUser.id){if(selectedUser.isManager){this.currentRootId=selectedUser.id;this.currentTreeUrl=this.reporteesEndpoint+selectedUser.id;this.rendered=false;this.render();}else{var nodeId='jstree_node_'+selectedUser.user_name;if(this.jsTree.jstree('get_selected').attr('id')!=nodeId){this.selectJSTreeNode(nodeId)}}}},selectJSTreeNode:function(nodeId){this.jsTree.jstree('deselect_all');this.jsTree.jstree('select_node','#'+nodeId);},_recursiveReplaceHTMLChars:function(data,self){_.each(data,function(entry,index){if(entry.data){data[index].data=replaceHTMLChars(entry.data);if(entry.children){_.each(entry.children,function(childEntry,index2){entry.children[index2]=self._recursiveReplaceHTMLChars([childEntry]);if(childEntry.metadata.id==this.selectedUser.id){childEntry.data=app.utils.formatString(app.lang.get('LBL_MY_OPPORTUNITIES','Forecasts'),[childEntry.data]);}},this);}}},this);return data;},_renderHtml:function(ctx,options){app.view.View.prototype._renderHtml.call(this,ctx,options);var self=this;var treeData;app.api.call('read',self.currentTreeUrl,null,{success:function(data){if(!jQuery.isArray(data)){data=[data];}
treeData=self._recursiveReplaceHTMLChars(data,self);self.jsTree=$(".jstree-sugar").jstree({"plugins":["json_data","ui","crrm","types","themes"],"json_data":{"data":treeData},"ui":{"initially_select":['jstree_node_'+self.context.forecasts.get('selectedUser').user_name]},"types":{"types":{"types":{"parent_link":{},"manager":{},"my_opportunities":{},"rep":{},"root":{}}}}}).on("select_node.jstree",function(event,data){var jsData=data.inst.get_json();var nodeType=jsData[0].attr.rel;var userData=jsData[0].metadata;var contextUser=self.context.forecasts.get("selectedUser");var showOpps=false;if(nodeType=="my_opportunities"||nodeType=="rep"){showOpps=true}
var selectedUser={'id':userData.id,'user_name':userData.user_name,'full_name':userData.full_name,'first_name':userData.first_name,'last_name':userData.last_name,'isManager':(nodeType!='rep'),'showOpps':showOpps};self.context.forecasts.set("selectedUser",selectedUser);});if(treeData){var showTree=false;var rootId=-1;if(treeData.length==1){rootId=treeData[0].metadata.id;if(treeData[0].children.length>0){showTree=true;}}
else if(treeData.length==2){rootId=treeData[1].metadata.id;}
self.currentRootId=rootId;}
$("#people").addClass("jstree-sugar");}});}})