<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'j_discount_modified_user' => 
  array (
    'id' => '4de4b8d0-a8cd-ae5b-8e13-55f917600c0b',
    'relationship_name' => 'j_discount_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Discount',
    'rhs_table' => 'j_discount',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_discount_created_by' => 
  array (
    'id' => '4e1cb01b-f417-a3da-3e17-55f917e98b5a',
    'relationship_name' => 'j_discount_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Discount',
    'rhs_table' => 'j_discount',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_discount_assigned_user' => 
  array (
    'id' => '4f037452-49f3-1417-0e12-55f917c4db51',
    'relationship_name' => 'j_discount_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Discount',
    'rhs_table' => 'j_discount',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_discount_j_discount_1' => 
  array (
    'id' => '4ea52ec6-2d92-d334-aff4-55f917de5c5f',
    'relationship_name' => 'j_discount_j_discount_1',
    'lhs_module' => 'J_Discount',
    'lhs_table' => 'j_discount',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Discount',
    'rhs_table' => 'j_discount',
    'rhs_key' => 'id',
    'join_table' => 'j_discount_j_discount_1_c',
    'join_key_lhs' => 'j_discount_j_discount_1j_discount_ida',
    'join_key_rhs' => 'j_discount_j_discount_1j_discount_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'j_discount_j_partnership_1' => 
  array (
    'id' => '4eefea7f-0a88-8868-a474-55f917ad82ce',
    'relationship_name' => 'j_discount_j_partnership_1',
    'lhs_module' => 'J_Discount',
    'lhs_table' => 'j_discount',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Partnership',
    'rhs_table' => 'j_partnership',
    'rhs_key' => 'id',
    'join_table' => 'j_discount_j_partnership_1_c',
    'join_key_lhs' => 'j_discount_j_partnership_1j_discount_ida',
    'join_key_rhs' => 'j_discount_j_partnership_1j_partnership_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'j_payment_j_discount_1' => 
  array (
    'id' => '4fbe9e6a-95c9-e7d7-9ae4-55f917e32be6',
    'relationship_name' => 'j_payment_j_discount_1',
    'lhs_module' => 'J_Payment',
    'lhs_table' => 'j_payment',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Discount',
    'rhs_table' => 'j_discount',
    'rhs_key' => 'id',
    'join_table' => 'j_payment_j_discount_1_c',
    'join_key_lhs' => 'j_payment_j_discount_1j_payment_ida',
    'join_key_rhs' => 'j_payment_j_discount_1j_discount_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);