<?php
/*********************************************************************************
* By installing or using this file, you are confirming on behalf of the entity
* subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
* the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
* http://www.sugarcrm.com/master-subscription-agreement
*
* If Company is not bound by the MSA, then by installing or using this file
* you are agreeing unconditionally that Company will be bound by the MSA and
* certifying that you have authority to bind Company accordingly.
*
* Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
********************************************************************************/

$dictionary['C_DeliveryRevenue'] = array(
    'table'=>'c_deliveryrevenue',
    'audited'=>false,
    'duplicate_merge'=>true,
    'fields'=>array (
        'name' =>
        array (
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '50',
            'unified_search' => false,
            'full_text_search' =>
            array (
                'boost' => 3,
            ),
            'required' => true,
            'importable' => 'true',
            'merge_filter' => 'selected',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'audited' => false,
            'reportable' => true,
            'calculated' => false,
            'size' => '20',
        ),
        'passed' =>
        array (
            'required' => false,
            'name' => 'passed',
            'vname' => 'LBL_PASSED',
            'type' => 'bool',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'amount' =>
        array (
            'required' => false,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '26',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'type' =>
        array (
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 20,
            'size' => '20',
            'options' => 'data_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'revenue_type' =>
        array (
            'required' => true,
            'name' => 'revenue_type',
            'vname' => 'LBL_REVENUE_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 30,
            'size' => '20',
            'options' => 'revenue_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'status' =>
        array (
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Paid',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 10,
            'size' => '20',
            'options' => 'status_payments_list_2',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'duration' =>
        array (
            'required' => false,
            'name' => 'duration',
            'vname' => 'LBL_DURATION',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'date_input' =>
        array (
            'required' => false,
            'name' => 'date_input',
            'vname' => 'LBL_DATE_INPUT',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'cost_per_hour' =>
        array (
            'required' => false,
            'name' => 'cost_per_hour',
            'vname' => 'LBL_COST_PER_HOUR',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '13',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => '2',
        ),

        // Relationship Student ( 1 - n ) Delivery Revenue - Lap Nguyen
        'student_name' => array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'student_name',
            'vname'     => 'LBL_STUDENT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'student_id',
            'join_name' => 'contacts',
            'link'      => 'student_revenue',
            'table'     => 'contacts',
            'isnull'    => 'true',
            'module'    => 'Contacts',
        ),

        'student_id' => array (
            'name'              => 'student_id',
            'rname'             => 'id',
            'vname'             => 'LBL_STUDENT_ID',
            'type'              => 'id',
            'table'             => 'contacts',
            'isnull'            => 'true',
            'module'            => 'Contacts',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),

        'student_revenue' => array (
            'name'          => 'student_revenue',
            'type'          => 'link',
            'relationship'  => 'student_revenue',
            'module'        => 'Contacts',
            'bean_name'     => 'Contacts',
            'source'        => 'non-db',
            'vname'         => 'LBL_STUDENT_NAME',
        ),
        // Relationship Student ( 1 - n ) Delivery Revenue

        // Relationship Situation ( 1 - n ) Delivery Revenue - Lap Nguyen
        'situation_name' => array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'situation_name',
            'vname'     => 'LBL_SITUATION_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'situation_id',
            'join_name' => 'J_StudentSituations',
            'link'      => 'ju_situation',
            'table'     => 'j_studentsituations',
            'isnull'    => 'true',
            'module'    => 'J_StudentSituations',
        ),

        'situation_id' => array (
            'name'              => 'situation_id',
            'rname'             => 'id',
            'vname'             => 'LBL_SITUATION_NAME',
            'type'              => 'id',
            'table'             => 'j_studentsituations',
            'isnull'            => 'true',
            'module'            => 'J_StudentSituations',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),

        'ju_situation' => array (
            'name'          => 'ju_situation',
            'type'          => 'link',
            'relationship'  => 'situation_revenues',
            'module'        => 'J_StudentSituations',
            'bean_name'     => 'J_StudentSituations',
            'source'        => 'non-db',
            'vname'         => 'LBL_SITUATION_NAME',
        ),
        // Relationship Student ( 1 - n ) Delivery Revenue

        // Relationship Lead ( 1 - n ) Delivery Revenue - Lap Nguyen
        'lead_name' => array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'lead_name',
            'vname'     => 'LBL_LEAD_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'lead_id',
            'join_name' => 'leads',
            'link'      => 'lead_revenue',
            'table'     => 'leads',
            'isnull'    => 'true',
            'module'    => 'Leads',
        ),

        'lead_id' => array (
            'name'              => 'lead_id',
            'rname'             => 'id',
            'vname'             => 'LBL_LEAD_ID',
            'type'              => 'id',
            'table'             => 'leads',
            'isnull'            => 'true',
            'module'            => 'Leads',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),
        'total_allocated_hours' =>
        array (
            'required' => false,
            'name' => 'total_allocated_hours',
            'vname' => 'LBL_ALLOCATED_HOURS',
            'type' => 'decimal',
            'len' => '6',
            'precision' => '2',
        ),
        'total_allocated_amount' =>
        array (
            'required' => false,
            'name' => 'total_allocated_amount',
            'vname' => 'LBL_ALLOCATED_AMOUNT',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'lead_revenue' => array (
            'name'          => 'lead_revenue',
            'type'          => 'link',
            'relationship'  => 'lead_revenue',
            'module'        => 'Leads',
            'bean_name'     => 'Leads',
            'source'        => 'non-db',
            'vname'         => 'LBL_LEAD_NAME',
        ),
        // Relationship Lead ( 1 - n ) Delivery Revenue

        // Relationship Session ( 1 - n ) Delivery Revenue - Lap Nguyen
        'session_name' => array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'session_name',
            'vname'     => 'LBL_SESSION_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'session_id',
            'join_name' => 'meetings',
            'link'      => 'session_revenue',
            'table'     => 'meetings',
            'isnull'    => 'true',
            'module'    => 'Meetings',
        ),
        // Doanh thu bổ sung cho - Xử lý case mất giờ tháng đã chốt doanh thu. TH 2 trong Fix_data_2
        'sss_id' => array (
            'name'              => 'sss_id',
            'rname'             => 'id',
            'vname'             => 'LBL_SSS_ID',
            'type'              => 'id',
            'table'             => 'meetings',
            'isnull'            => 'true',
            'module'            => 'Meetings',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),

        'session_id' => array (
            'name'              => 'session_id',
            'rname'             => 'id',
            'vname'             => 'LBL_SESSION_ID',
            'type'              => 'id',
            'table'             => 'meetings',
            'isnull'            => 'true',
            'module'            => 'Meetings',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),

        'session_revenue' => array (
            'name'          => 'session_revenue',
            'type'          => 'link',
            'relationship'  => 'session_revenue',
            'module'        => 'Meetings',
            'bean_name'     => 'Meetings',
            'source'        => 'non-db',
            'vname'         => 'LBL_SESSION_NAME',
        ),
        // Relationship Session ( 1 - n ) Delivery Revenue

        //Relationship Enrollment (1 - n) Delivery
        'enrollment_name' =>
        array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'enrollment_name',
            'vname'     => 'LBL_ENROLLMENT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'enrollment_id',
            'link'      => 'enrollments',
            'table'     => 'opportunities',
            'isnull'    => 'true',
            'module'    => 'Opportunities',
        ),
        'enrollment_id' =>
        array (
            'name'              => 'enrollment_id',
            'rname'             => 'id',
            'vname'             => 'LBL_ENROLLMENT_NAME',
            'type'              => 'id',
            'table'             => 'opportunities',
            'isnull'            => 'true',
            'module'            => 'Opportunities',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),
        'enrollments' =>
        array (
            'name'          => 'enrollments',
            'type'          => 'link',
            'relationship'  => 'enrollment_delivery',
            'module'        => 'Opportunities',
            'bean_name'     => 'Opportunity',
            'source'        => 'non-db',
            'vname'         => 'LBL_ENROLLMENT_NAME',
        ),
        //END: Field Kind of cource

        //Relationship Contract (1 - n) Delivery
        'contract_name' =>
        array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'contract_name',
            'vname'     => 'LBL_CONTRACT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'contract_id',
            'link'      => 'contracts_link',
            'table'     => 'contracts',
            'isnull'    => 'true',
            'module'    => 'Contracts',
        ),
        'contract_id' =>
        array (
            'name'              => 'contract_id',
            'rname'             => 'id',
            'vname'             => 'LBL_CONTRACT_NAME',
            'type'              => 'id',
            'table'             => 'contracts',
            'isnull'            => 'true',
            'module'            => 'Contracts',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),
        'contracts_link' =>
        array (
            'name'          => 'contracts_link',
            'type'          => 'link',
            'relationship'  => 'contract_delivery',
            'module'        => 'Contracts',
            'bean_name'     => 'Contract',
            'source'        => 'non-db',
            'vname'         => 'LBL_CONTRACT_NAME',
        ),

        // Field for  Junior - Tung Bui 30/11/2015
        'ju_payment_id' =>
        array (
            'name' => 'ju_payment_id',
            'vname' => 'LBL_JU_PAYMENT_ID',
            'type' => 'id',
            'required'=>false,
            'reportable'=>false,
            'comment' => ''
        ),
        'ju_payment_name' => array (
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'ju_payment_name',
            'vname'     => 'LBL_JU_PAYMENT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'ju_payment_id',
            'join_name' => 'j_payment',
            'link'      => 'ju_payment_link',
            'table'     => 'j_payment',
            'isnull'    => 'true',
            'module'    => 'J_Payment',
        ),
        'ju_payment_link' => array (
            'name'          => 'ju_payment_link',
            'type'          => 'link',
            'relationship'  => 'ju_payment_revenue',
            'module'        => 'J_Payment',
            'bean_name'     => 'J_Payment',
            'source'        => 'non-db',
            'vname'         => 'LBL_JU_PAYMENT_NAME',
        ),
        // END Field for Junior
    ),
    'relationships'=>array (
    ),
    'optimistic_locking'=>true,
    'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('C_DeliveryRevenue','C_DeliveryRevenue', array('basic','team_security','assignable'));