<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'c_classes_modified_user' => 
  array (
    'id' => '572376f2-846e-2848-93d0-547ddb4af416',
    'relationship_name' => 'c_classes_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Classes',
    'rhs_table' => 'c_classes',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_classes_created_by' => 
  array (
    'id' => '574f5088-4acb-9e44-2767-547ddb4e0d72',
    'relationship_name' => 'c_classes_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Classes',
    'rhs_table' => 'c_classes',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_classes_assigned_user' => 
  array (
    'id' => '57e4fa04-ff9c-15c5-eed3-547ddb04507a',
    'relationship_name' => 'c_classes_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Classes',
    'rhs_table' => 'c_classes',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'classes_meetings' => 
  array (
    'id' => '58089943-5abc-379b-3511-547ddb044443',
    'relationship_name' => 'classes_meetings',
    'lhs_module' => 'C_Classes',
    'lhs_table' => 'c_classes',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'class_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'class_gradebooks' => 
  array (
    'id' => '582ee30b-bd9c-8cb9-6a3c-547ddb8ba59e',
    'relationship_name' => 'class_gradebooks',
    'lhs_module' => 'C_Classes',
    'lhs_table' => 'c_classes',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Gradebook',
    'rhs_table' => 'c_gradebook',
    'rhs_key' => 'class_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_classes_contacts_1' => 
  array (
    'id' => '2fe70310-6851-ac5e-d2fb-547ddbf4c707',
    'relationship_name' => 'c_classes_contacts_1',
    'lhs_module' => 'C_Classes',
    'lhs_table' => 'c_classes',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'c_classes_contacts_1_c',
    'join_key_lhs' => 'c_classes_contacts_1c_classes_ida',
    'join_key_rhs' => 'c_classes_contacts_1contacts_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_classes_c_rooms_1' => 
  array (
    'id' => '32e90bbc-9e0b-6369-0dc3-547ddbb02f29',
    'relationship_name' => 'c_classes_c_rooms_1',
    'lhs_module' => 'C_Classes',
    'lhs_table' => 'c_classes',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Rooms',
    'rhs_table' => 'c_rooms',
    'rhs_key' => 'id',
    'join_table' => 'c_classes_c_rooms_1_c',
    'join_key_lhs' => 'c_classes_c_rooms_1c_classes_ida',
    'join_key_rhs' => 'c_classes_c_rooms_1c_rooms_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_classes_c_teachers_1' => 
  array (
    'id' => '35c8098f-2830-7d42-bd88-547ddb68639d',
    'relationship_name' => 'c_classes_c_teachers_1',
    'lhs_module' => 'C_Classes',
    'lhs_table' => 'c_classes',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Teachers',
    'rhs_table' => 'c_teachers',
    'rhs_key' => 'id',
    'join_table' => 'c_classes_c_teachers_1_c',
    'join_key_lhs' => 'c_classes_c_teachers_1c_classes_ida',
    'join_key_rhs' => 'c_classes_c_teachers_1c_teachers_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_classes_opportunities_1' => 
  array (
    'id' => '38b50acc-ef45-3142-b353-547ddb21df95',
    'relationship_name' => 'c_classes_opportunities_1',
    'lhs_module' => 'C_Classes',
    'lhs_table' => 'c_classes',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'c_classes_opportunities_1_c',
    'join_key_lhs' => 'c_classes_opportunities_1c_classes_ida',
    'join_key_rhs' => 'c_classes_opportunities_1opportunities_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_programs_c_classes_1' => 
  array (
    'id' => '50fc0637-89ae-cb3f-fff8-547ddbf4c642',
    'relationship_name' => 'c_programs_c_classes_1',
    'lhs_module' => 'C_Programs',
    'lhs_table' => 'c_programs',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Classes',
    'rhs_table' => 'c_classes',
    'rhs_key' => 'id',
    'join_table' => 'c_programs_c_classes_1_c',
    'join_key_lhs' => 'c_programs_c_classes_1c_programs_ida',
    'join_key_rhs' => 'c_programs_c_classes_1c_classes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_classes_contracts_1' => 
  array (
    'rhs_label' => 'Contracts',
    'lhs_label' => 'Classes',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'C_Classes',
    'rhs_module' => 'Contracts',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'c_classes_contracts_1',
  ),
);