/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({events:{'click [class*="orderBy"]':'setOrderBy','mouseenter tr':'showActions','mouseleave tr':'hideActions'},calculateRelativeWidths:function(){var totalWidth=0;for(var p in this.meta.panels){for(var f in this.meta.panels[p].fields){var field=this.meta.panels[p].fields[f];totalWidth+=parseInt(field.width)||10;}
var adjustment=100 / totalWidth;for(var f in this.meta.panels[p].fields){var field=this.meta.panels[p].fields[f];field.width=Math.floor((parseInt(field.width)||10)*adjustment);}}},_renderHtml:function(){this.calculateRelativeWidths();this.collection.newRecords=_.find(this.collection.models,function(model){return model.old===true;})
app.view.View.prototype._renderHtml.call(this);this.layout.off("list:search:fire",null,this);this.layout.off("list:paginate:success",null,this);this.layout.on("list:search:fire",this.fireSearch,this);this.layout.on("list:paginate:success",this.render,this);this.layout.off("list:filter:toggled",null,this);this.layout.on("list:filter:toggled",this.filterToggled,this);this.limit=this.context.get('limit')?this.context.get('limit'):null;},filterToggled:function(isOpened){this.filterOpened=isOpened;},fireSearch:function(term){var options={limit:this.limit||null,params:{q:term},fields:this.collection.fields||{}};this.collection.fetch(options);},setOrderBy:function(event){var orderMap,collection,fieldName,nOrder,options,eventTarget,orderBy;var self=this;self.orderBy=self.orderBy||{};orderMap={"desc":"_desc","asc":"_asc"};collection=self.collection;eventTarget=self.$(event.target);fieldName=eventTarget.data('fieldname');orderBy=eventTarget.data('orderby');if(!orderBy){orderBy=eventTarget.data('fieldname');}
if(!collection.orderBy){collection.orderBy={field:"",direction:"",columnName:""};}
nOrder="desc";if(orderBy===collection.orderBy.field){if(collection.orderBy.direction==="desc"){nOrder="asc";}
collection.orderBy.direction=nOrder;}else{collection.orderBy.field=orderBy;collection.orderBy.direction="desc";}
collection.orderBy.columnName=fieldName;self.orderBy.field=orderBy;self.orderBy.direction=orderMap[collection.orderBy.direction];self.orderBy.columnName=fieldName;options=self.filterOpened?self.getSearchOptions():{};options.limit=self.limit||null;app.alert.show('loading_'+self.cid,{level:'process',title:app.lang.getAppString('LBL_PORTAL_LOADING')});options.success=function(){app.alert.dismiss('loading_'+self.cid);self.render();};collection.fetch(options);},getSearchOptions:function(){var collection,options,previousTerms,term='';collection=this.context.get('collection');if(app.cache.has('previousTerms')){previousTerms=app.cache.get('previousTerms');if(previousTerms){term=previousTerms[this.module];}}
options={params:{q:term},fields:collection.fields?collection.fields:this.collection};return options;},showActions:function(e){$(e.currentTarget).children("td").children("span").children(".btn-group").show();},hideActions:function(e){$(e.currentTarget).children("td").children("span").children(".btn-group").hide();},bindDataChange:function(){if(this.collection){this.collection.on("reset",this.render,this);}}})