<?php
// created: 2015-07-03 09:27:36
$dictionary["J_School"]["fields"]["j_school_j_school_1"] = array (
  'name' => 'j_school_j_school_1',
  'type' => 'link',
  'relationship' => 'j_school_j_school_1',
  'source' => 'non-db',
  'module' => 'J_School',
  'bean_name' => 'J_School',
  'vname' => 'LBL_J_SCHOOL_J_SCHOOL_1_FROM_J_SCHOOL_L_TITLE',
  'id_name' => 'j_school_j_school_1j_school_ida',
);
$dictionary["J_School"]["fields"]["j_school_j_school_1"] = array (
  'name' => 'j_school_j_school_1',
  'type' => 'link',
  'relationship' => 'j_school_j_school_1',
  'source' => 'non-db',
  'module' => 'J_School',
  'bean_name' => 'J_School',
  'vname' => 'LBL_J_SCHOOL_J_SCHOOL_1_FROM_J_SCHOOL_R_TITLE',
  'id_name' => 'j_school_j_school_1j_school_ida',
);
$dictionary["J_School"]["fields"]["j_school_j_school_1_name"] = array (
  'name' => 'j_school_j_school_1_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_J_SCHOOL_J_SCHOOL_1_FROM_J_SCHOOL_R_TITLE',
  'save' => true,
  'id_name' => 'j_school_j_school_1j_school_ida',
  'link' => 'j_school_j_school_1',
  'table' => 'j_school',
  'module' => 'J_School',
  'rname' => 'name',
);
$dictionary["J_School"]["fields"]["j_school_j_school_1_name"] = array (
  'name' => 'j_school_j_school_1_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_J_SCHOOL_J_SCHOOL_1_FROM_J_SCHOOL_L_TITLE',
  'save' => true,
  'id_name' => 'j_school_j_school_1j_school_ida',
  'link' => 'j_school_j_school_1',
  'table' => 'j_school',
  'module' => 'J_School',
  'rname' => 'name',
);
$dictionary["J_School"]["fields"]["j_school_j_school_1j_school_ida"] = array (
  'name' => 'j_school_j_school_1j_school_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_J_SCHOOL_J_SCHOOL_1_FROM_J_SCHOOL_R_TITLE_ID',
  'id_name' => 'j_school_j_school_1j_school_ida',
  'link' => 'j_school_j_school_1',
  'table' => 'j_school',
  'module' => 'J_School',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'left',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
$dictionary["J_School"]["fields"]["j_school_j_school_1j_school_ida"] = array (
  'name' => 'j_school_j_school_1j_school_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_J_SCHOOL_J_SCHOOL_1_FROM_J_SCHOOL_L_TITLE_ID',
  'id_name' => 'j_school_j_school_1j_school_ida',
  'link' => 'j_school_j_school_1',
  'table' => 'j_school',
  'module' => 'J_School',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'left',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
