<?php
/*********************************************************************************
* By installing or using this file, you are confirming on behalf of the entity
* subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
* the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
* http://www.sugarcrm.com/master-subscription-agreement
*
* If Company is not bound by the MSA, then by installing or using this file
* you are agreeing unconditionally that Company will be bound by the MSA and
* certifying that you have authority to bind Company accordingly.
*
* Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
********************************************************************************/

$dictionary['J_Inventory'] = array(
    'table'=>'j_inventory',
    'audited'=>true,
    'duplicate_merge'=>true,
    'fields'=>array (
        'request_no' =>
        array (
            'required' => false,
            'name' => 'request_no',
            'vname' => 'LBL_REQUEST_NO',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '50',
            'size' => '20',
        ),
        'status' =>
        array (
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Confirmed',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'status_inventory_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'date_create' =>
        array (
            'required' => true,
            'name' => 'date_create',
            'vname' => 'LBL_DATE_CREATE',
            'type' => 'date',
            'massupdate' => 0,
            'display_default' => 'now',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
        ),
        'type' =>
        array (
            'required' => false,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'type_inventory_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'from_inventory_list' =>
        array (
            'required' => false,
            'name' => 'from_inventory_list',
            'vname' => 'LBL_FROM_INVENTORY_LIST',
            'type' => 'enum',
            'massupdate' => 0,
            //'default' => 'Teams',
            //'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'from_inventory_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'to_inventory_list' =>
        array (
            'required' => false,
            'name' => 'to_inventory_list',
            'vname' => 'LBL_TO_INVENTORY_LIST',
            'type' => 'enum',
            'massupdate' => 0,
            //'default' => 'Center',
            // 'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'to_inventory_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'total_quantity' =>
        array (
            'required' => false,
            'name' => 'total_quantity',
            'vname' => 'LBL_TOTAL_QUANTITY',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
        ),
        'total_amount' =>
        array (
            'required' => false,
            'name' => 'total_amount',
            'vname' => 'LBL_TOTAL_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
        ),
        //Add Relationship Inventory - Inventory detail
        'inventorydetail_link'=>array(
            'name' => 'inventorydetail_link',
            'type' => 'link',
            'relationship' => 'inventory_inventorydetails',
            'module' => 'J_Inventorydetail',
            'bean_name' => 'J_Inventorydetail',
            'source' => 'non-db',
            'vname' => 'LBL_INVENTORYDETAIL',
        ),
        //END
        'month_report'  =>
        array (
            'required' => false,
            'name' => 'month_report',
            'vname' => 'LBL_MONTH',
            'type' => 'enum',
            'options' => 'month_report_list',
        ),
        'year_report'  =>
        array (
            'required' => false,
            'name' => 'year_report',
            'vname' => 'LBL_YEAR',
            'type' => 'varchar',
        ),
    ),
    'relationships'=>array (
    //Add Relationship Inventory - Inventory detail
        'inventory_inventorydetails' => array(
            'lhs_module'        => 'J_Inventory',
            'lhs_table'            => 'j_inventory',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_Inventorydetail',
            'rhs_table'            => 'j_inventorydetail',
            'rhs_key'            => 'inventory_id',
            'relationship_type'    => 'one-to-many',
        ),
    //END
    ),
    'optimistic_locking'=>true,
    'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('J_Inventory','J_Inventory', array('basic','team_security','assignable'));