/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({url:'rest/v10/ForecastWorksheets',show:false,viewModule:{},selectedUser:{},timePeriod:'',gTable:'',gTableDefs:{},aaSorting:[],isExpandableRows:'',isEditableWorksheet:false,_collection:{},columnDefs:[],mgrNeedsCommitted:false,commitButtonEnabled:false,commitFromSafeFetch:false,fetchInProgress:false,dirtyModels:new Backbone.Collection(),dirtyTimeperiod:'',dirtyUser:'',initialize:function(options){var self=this;self.gTableDefs={"bAutoWidth":false,"aoColumnDefs":self.columnDefs,"aaSorting":self.aaSorting,"bInfo":false,"bPaginate":false};this.viewModule=app.viewModule;this.isExpandableRows=false;app.view.View.prototype.initialize.call(this,options);this._collection=this.context.forecasts.worksheet;this.selectedUser={id:app.user.get('id'),"isManager":app.user.get('isManager'),"showOpps":false};this.timePeriod=app.defaultSelections.timeperiod_id.id;this.updateWorksheetBySelectedRanges(app.defaultSelections.ranges);this._collection.url=this.createURL();},createURL:function(){var url=this.url;var args={};if(this.timePeriod){args['timeperiod_id']=this.timePeriod;}
if(this.selectedUser)
{args['user_id']=this.selectedUser.id;}
url=app.api.buildURL('ForecastWorksheets','','',args);return url;},_renderField:function(field){this._createFieldColumnDef(field.def);app.view.View.prototype._renderField.call(this,field);if(this.isEditableWorksheet===true&&field.viewName!="edit"&&field.def.clickToEdit===true&&!_.contains(this.context.forecasts.config.get("sales_stage_won"),field.model.get('sales_stage'))&&!_.contains(this.context.forecasts.config.get("sales_stage_lost"),field.model.get('sales_stage'))){new app.view.ClickToEditField(field,this);}},_createFieldColumnDef:function(field){if(!_.isEmpty(this.columnDefs)&&_.find(this.columnDefs,_.bind(function(obj){return obj.sName==this.name},field))){return;}
if(field.enabled){var fieldDef={"sName":field.name,"aTargets":[this.columnDefs.length],"bVisible":this.checkConfigForColumnVisibility(field.name)};if(!_.isUndefined(field.type)){switch(field.type)
{case"commitStage":case"enum":case"bool":fieldDef["bSortable"]=false;break;case"int":case"editableInt":case"currency":case"editableCurrency":fieldDef["sSortDataType"]="dom-number";fieldDef["sType"]="numeric";break;}
switch(field.name){case"likely_case":fieldDef["sClass"]="number likely";fieldDef["sWidth"]="22%";break;case"best_case":fieldDef["sClass"]="number best";fieldDef["sWidth"]="22%";break;case"worst_case":fieldDef["sClass"]="number worst";fieldDef["sWidth"]="22%";break;case"probability":fieldDef["sClass"]="number";break;}}
this.columnDefs.push(fieldDef);}},unbindData:function(){if(this._collection){this._collection.off(null,null,this)};if(this.context.forecasts){this.context.forecasts.off(null,null,this)};if(this.context.forecasts.config){this.context.forecasts.config.off(null,null,this)};if(this.context.forecasts.worksheet){this.context.forecasts.worksheet.off(null,null,this)};$(window).unbind("beforeunload");app.view.View.prototype.unbindData.call(this);},isDirty:function(){return(this.dirtyModels.length>0);},saveWorksheet:function(isDraft){var totalToSave=0;if(this.showMe()){var self=this,saveCount=0;totalToSave=self.dirtyModels.length;if(this.isDirty()){self.dirtyModels.each(function(model){model.set({"draft":(isDraft&&isDraft==true)?1:0,"timeperiod_id":self.dirtyTimeperiod||self.timePeriod,"current_user":self.dirtyUser.id||self.selectedUser.id},{silent:true});model.url=self.url.split("?")[0]+"/"+model.get("id");model.save({},{success:function(){saveCount++;if(totalToSave===saveCount){self.context.forecasts.trigger('forecasts:worksheet:saved',totalToSave,'rep_worksheet',isDraft);}},silent:true});});self.cleanUpDirtyModels();}else{this.context.forecasts.trigger('forecasts:worksheet:saved',totalToSave,'rep_worksheet',isDraft);}}
return totalToSave},cleanUpDirtyModels:function(){this.dirtyModels.reset();this.dirtyTimeperiod='';this.dirtyUser='';},bindDataChange:function(params){var self=this;if(this._collection){this._collection.on("reset",function(){self.cleanUpDirtyModels();self.render();},this);this._collection.on("change",function(model,changed){if(_.include(_.keys(changed.changes),'commit_stage')){this.gTable.fnDestroy();this.gTable=this.$('.worksheetTable').dataTable(self.gTableDefs);}
this.dirtyModels.add(model);this.context.forecasts.trigger('forecasts:worksheet:dirty',model,changed);},this);}
if(this.context.forecasts){this.context.forecasts.on("change:selectedUser",function(context,selectedUser){this.updateWorksheetBySelectedUser(selectedUser);},this);this.context.forecasts.on("change:selectedTimePeriod",function(context,timePeriod){this.updateWorksheetBySelectedTimePeriod(timePeriod);},this);this.context.forecasts.on("change:selectedRanges",function(context,ranges){this.updateWorksheetBySelectedRanges(ranges);},this);this.context.forecasts.worksheet.on("change",function(){this.calculateTotals();},this);this.context.forecasts.on("forecasts:committed:saved",function(){if(this.showMe()){var model=this.context.forecasts.worksheet;model.url=this.createURL();this.safeFetch();if(!this.commitFromSafeFetch){this.mgrNeedsCommitted=true;}
else{this.commitFromSafeFetch=false;}}},this);this.context.forecasts.on("forecasts:commitButtons:enabled",function(){if(_.isEqual(app.user.get('id'),self.selectedUser.id)){self.commitButtonEnabled=true;}},this);this.context.forecasts.on("forecasts:commitButtons:disabled",function(){self.commitButtonEnabled=false;},this);this.context.forecasts.on('forecasts:worksheet:saveWorksheet',function(isDraft){this.saveWorksheet(isDraft);},this);this.context.forecasts.config.on('change:buckets_dom change:forecast_ranges',this.render,this);$(window).bind("beforeunload",function(){if(self.isDirty()){return app.lang.get("LBL_WORKSHEET_SAVE_CONFIRM_UNLOAD","Forecasts");}
else if(!_.isUndefined(self.context.forecasts)&&(self.context.forecasts.get("currentWorksheet")=="worksheet")&&self.selectedUser.isManager&&self.context.forecasts.config.get("show_forecasts_commit_warnings")){if(self.commitButtonEnabled){var msg=app.lang.get("LBL_WORKSHEET_COMMIT_CONFIRM","Forecasts").split("<br>");return msg[0];}
else if(self.mgrNeedsCommitted){return app.lang.get("LBL_WORKSHEET_COMMIT_ALERT","Forecasts");}}});}},setColumnVisibility:function(cols,value,ctx){var aoColumns=ctx.gTable.fnSettings().aoColumns;for(var i in cols){var columnName=cols[i];for(var k in aoColumns){if(aoColumns[k].sName==columnName){this.gTable.fnSetColumnVis(k,value==1);break;}}}},checkConfigForColumnVisibility:function(colKey){return app.forecasts.utils.getColumnVisFromKeyMap(colKey,this.name,this.context.forecasts.config);},safeFetch:function(fetch){if(this.fetchInProgress){return;}
this.fetchInProgress=true;if(_.isUndefined(fetch))
{fetch=true;}
var collection=this._collection;var self=this;if(self.isDirty()){if(confirm(app.lang.get("LBL_WORKSHEET_SAVE_CONFIRM","Forecasts"))){self.context.forecasts.set({reloadCommitButton:true});var svWkFn=function(){self.context.forecasts.off('forecasts:worksheet:saved',svWkFn);collection.fetch();};self.context.forecasts.on('forecasts:worksheet:saved',svWkFn);this.saveWorksheet()}
else{collection.isDirty=false;self.context.forecasts.set({reloadCommitButton:true});if(fetch){collection.fetch();}}}
else if(self.selectedUser.isManager&&(self.context.forecasts.get("currentWorksheet")=="worksheet")&&self.context.forecasts.config.get("show_forecasts_commit_warnings")){if(self.commitButtonEnabled){var msg=app.lang.get("LBL_WORKSHEET_COMMIT_CONFIRM","Forecasts").split("<br>");if(confirm(msg[0]+"\n\n"+msg[1])){self.context.forecasts.trigger("forecasts:commitButtons:triggerCommit");self.commitFromSafeFetch=true;}
else{if(fetch){collection.fetch();}}}
else if(self.mgrNeedsCommitted){alert(app.lang.get("LBL_WORKSHEET_COMMIT_ALERT","Forecasts"));self.mgrNeedsCommitted=false;if(fetch){collection.fetch();}}
else{if(fetch){collection.fetch();}}}
else{if(fetch){collection.fetch();}}
this.fetchInProgress=false;},_render:function(){var self=this;if(!this.showMe()){return false;}
$("#view-sales-rep").addClass('show').removeClass('hide');$("#view-manager").addClass('hide').removeClass('show');this.context.forecasts.set({currentWorksheet:"worksheet"});this.isEditableWorksheet=this.isMyWorksheet();this.columnDefs=[];app.view.View.prototype._render.call(this);if(_.isEmpty(this.columnDefs)){_.each(this.options.meta.panels[0].fields,function(field){self._createFieldColumnDef(field);});}
this.gTableDefs['aoColumnDefs']=this.columnDefs;this.gTable=this.$('.worksheetTable').dataTable(this.gTableDefs);self.adjustCurrencyColumnWidths();self.calculateTotals();this.$el.find('td:has(span>input[type=checkbox])').addClass('center');self.context.forecasts.trigger("forecasts:worksheet:rendered");var enableCommit=self._collection.find(function(model){return!_.isEmpty(model.get("w_date_modified"))&&(new Date(model.get("w_date_modified"))<new Date(model.get("date_modified")))},this);if(_.isObject(enableCommit)){self.context.forecasts.trigger("forecasts:commitButtons:enabled");}
return this;},adjustCurrencyColumnWidths:function(){var likelyConverted=this.$el.find('.likely .converted'),likelyOriginal=this.$el.find('.likely label.original'),bestConverted=this.$el.find('.best .converted'),bestOriginal=this.$el.find('.best label.original'),worstConverted=this.$el.find('.worst .converted'),worstOriginal=this.$el.find('.worst label.original');var likelyWidths=likelyConverted.map(function(){return $(this).width();}).get();var likelyLabelWidths=likelyOriginal.map(function(){return $(this).width();}).get();var bestWidths=bestConverted.map(function(){return $(this).width();}).get();var bestLabelWidths=bestOriginal.map(function(){return $(this).width();}).get();var worstWidths=worstConverted.map(function(){return $(this).width();}).get();var worstLabelWidths=worstOriginal.map(function(){return $(this).width();}).get();likelyConverted.width(_.max(likelyWidths));likelyOriginal.width(_.max(likelyLabelWidths));bestConverted.width(_.max(bestWidths));bestOriginal.width(_.max(bestLabelWidths));worstConverted.width(_.max(worstWidths));worstOriginal.width(_.max(worstLabelWidths));this.$el.find('.number .likely').width(likelyConverted.width()+likelyOriginal.width());this.$el.find('.number .best').width(bestConverted.width()+bestOriginal.width());this.$el.find('.number .worst').width(worstConverted.width()+worstOriginal.width());},isMyWorksheet:function(){return _.isEqual(app.user.get('id'),this.selectedUser.id);},showMe:function(){var selectedUser=(this.isDirty()&&this.dirtyUser)?this.dirtyUser:this.selectedUser;return selectedUser.showOpps||!selectedUser.isManager;},calculateTotals:function(){var self=this,includedAmount=0,includedBest=0,includedWorst=0,overallAmount=0,overallBest=0,overallWorst=0,includedCount=0,lostCount=0,lostAmount=0,wonCount=0,wonAmount=0,totalCount=0;includedClosedCount=0;includedClosedAmount=0;if(!this.showMe()){this.context.forecasts.set({updatedTotals:{'amount':includedAmount,'best_case':includedBest,'worst_case':includedWorst,'overall_amount':overallAmount,'overall_best':overallBest,'overall_worst':overallWorst,'timeperiod_id':self.timePeriod,'lost_count':lostCount,'lost_amount':lostAmount,'won_count':wonCount,'won_amount':wonAmount,'included_opp_count':includedCount,'total_opp_count':totalCount,'closed_count':0,'closed_amount':0}},{silent:true});return false;}
var sales_stage_won_setting=this.context.forecasts.config.get('sales_stage_won')||[];var sales_stage_lost_setting=this.context.forecasts.config.get('sales_stage_lost')||[];_.each(self._collection.models,function(model){var won=_.include(sales_stage_won_setting,model.get('sales_stage'))
lost=_.include(sales_stage_lost_setting,model.get('sales_stage')),amount=parseFloat(model.get('likely_case')),commit_stage=model.get('commit_stage'),best=parseFloat(model.get('best_case')),base_rate=parseFloat(model.get('base_rate')),worst=parseFloat(model.get('worst_case')),worst_base=app.currency.convertWithRate(worst,base_rate),amount_base=app.currency.convertWithRate(amount,base_rate),best_base=app.currency.convertWithRate(best,base_rate);if(won){wonAmount=app.math.add(wonAmount,amount_base);wonCount++;}else if(lost){lostAmount=app.math.add(lostAmount,amount_base);lostCount++;}
if(commit_stage==='include'){includedAmount+=amount_base;includedBest+=best_base;includedWorst+=worst_base;includedCount++;if(won||lost){includedClosedCount++;includedClosedAmount=app.math.add(amount_base,includedClosedAmount);}}
overallAmount+=amount_base;overallBest+=best_base;overallWorst+=worst_base;});var totals={'amount':includedAmount,'best_case':includedBest,'worst_case':includedWorst,'overall_amount':overallAmount,'overall_best':overallBest,'overall_worst':overallWorst,'timeperiod_id':self.timePeriod,'lost_count':lostCount,'lost_amount':lostAmount,'won_count':wonCount,'won_amount':wonAmount,'included_opp_count':includedCount,'total_opp_count':self._collection.models.length,'closed_count':includedClosedCount,'closed_amount':includedClosedAmount};this.context.forecasts.unset("updatedTotals",{silent:true});this.context.forecasts.set("updatedTotals",totals);},updateWorksheetBySelectedUser:function(selectedUser){if(this.isDirty()){this.dirtyUser=this.selectedUser;}
this.safeFetch(false);this.selectedUser=selectedUser;if(!this.showMe()){return false;}
this._collection.url=this.createURL();this._collection.fetch();},updateWorksheetBySelectedRanges:function(params){var self=this,forecast_ranges_setting=this.context.forecasts.config.get('forecast_ranges')||'show_binary';if(!_.isUndefined($.fn.dataTableExt)){$.fn.dataTableExt.afnFiltering.splice(0,$.fn.dataTableExt.afnFiltering.length);if(!_.isEmpty(params)){$.fn.dataTableExt.afnFiltering.push(function(oSettings,aData,iDataIndex){if(oSettings.nTable==_.first($('.worksheetManagerTable'))){return true;}
var editable=self.isMyWorksheet(),selectVal,rowCategory=$(_.first(aData)),checkState;if(forecast_ranges_setting=='show_binary'){checkState=rowCategory.find('input').attr('checked');selectVal=((checkState=="checked")||(checkState=="on")||(checkState=="1"))?'include':'exclude';}else{if(rowCategory.find("select").length==0){selectVal=rowCategory.text().trim().toLowerCase();}else{selectVal=rowCategory.find("select")[0].value.toLowerCase();}}
self.context.forecasts.trigger('forecasts:worksheet:filtered');return(_.contains(params,selectVal));});}}
if(!_.isUndefined(this.gTable.fnDestroy)){this.gTable.fnDestroy();this.gTable=this.$('.worksheetTable').dataTable(self.gTableDefs);this.$el.find('td:has(span>input[type=checkbox])').addClass('center');this.context.forecasts.trigger('forecasts:worksheet:filtered');}},updateWorksheetBySelectedTimePeriod:function(params){if(this.isDirty()){this.dirtyTimeperiod=this.timePeriod;}
this.timePeriod=params.id;if(!this.showMe()){return false;}
this._collection.url=this.createURL();this.safeFetch(true);},getColumnHeadings:function(dTable,onlyVisible){if(onlyVisible!==false){onlyVisible=typeof onlyVisible!=='undefined'?onlyVisible:true;}
var cols=dTable.fnSettings().aoColumns;var retColumns=[];for(var i in cols){var title=this.app.lang.get(cols[i].sTitle);if(onlyVisible){if(cols[i].bVisible){retColumns.push(title);}}else{retColumns.push(title);}}
return retColumns;},hasColumn:function(columnName){var containsColumnName=false;var cols=this.gTable.fnSettings().aoColumns;for(var i in cols){if(cols[i].sName==columnName){containsColumnName=true;break;}}
return containsColumnName;}})