<?php
/*********************************************************************************
* By installing or using this file, you are confirming on behalf of the entity
* subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
* the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
* http://www.sugarcrm.com/master-subscription-agreement
*
* If Company is not bound by the MSA, then by installing or using this file
* you are agreeing unconditionally that Company will be bound by the MSA and
* certifying that you have authority to bind Company accordingly.
*
* Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
********************************************************************************/

$dictionary['J_Voucher'] = array(
    'table'=>'j_voucher',
    'audited'=>false,
    'duplicate_merge'=>true,
    'fields'=>array (
        'status' =>
        array (
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Inactive',
            'comments' => '',
            'help' => 'Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 10,
            'size' => '20',
            'options' => 'voucher_status_dom',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'discount_amount' =>
        array (
            'required' => false,
            'name' => 'discount_amount',
            'vname' => 'LBL_DISCOUNT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'default' => 0,
            'comments' => '',
            'help' => 'Discount Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'discount_percent' =>
        array (
            'required' => false,
            'name' => 'discount_percent',
            'vname' => 'LBL_DISCOUNT_PERCENT',
            'type' => 'decimal',
            'massupdate' => 0,
            'default' => 0,
            'comments' => '',
            'help' => 'Discount Percent',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '6',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
            'default' => '',
        ),
        'start_date' =>
        array (
            'required' => false,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Start Study',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'end_date' =>
        array (
            'required' => true,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'End Study',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'importable' => 'required',
        ),
        'use_time' =>
        array (
            'required' => false,
            'name' => 'use_time',
            'vname' => 'LBL_USE_TIME',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 10,
            'size' => '20',
            'options' => 'voucher_use_time',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'used_time' =>
        array (
            'required' => false,
            'name' => 'used_time',
            'vname' => 'LBL_USED_TIME',
            'type' => 'int',
            'len' => 5,
            'size' => '5',
            'default' => 0,
        ),
        'redempt_time' =>
        array (
            'required' => false,
            'name' => 'redempt_time',
            'vname' => 'LBL_REDEMPT_TIME',
            'type' => 'int',
            'len' => 5,
            'size' => '5',
            'default' => 0,
        ),
        'amount_per_used' =>
        array (
            'required' => false,
            'name' => 'amount_per_used',
            'vname' => 'LBL_AMOUNT_PER_USED',
            'type' => 'currency',
            'massupdate' => 0,
            'default' => 0,
            'comments' => '',
            'help' => 'Amount Referal',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'foc_type' =>
        array (
            'required' => false,
            'name' => 'foc_type',
            'vname' => 'LBL_FOC_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 30,
            'size' => '20',
            'options' => 'foc_type_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        //Custom Relationship . Student  - Voucher (1-n)  By Lap Nguyen
        'student_name' => array(
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'student_name',
            'vname'     => 'LBL_STUDENT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'student_id',
            'join_name' => 'contacts',
            'link'      => 'ju_contacts',
            'table'     => 'contacts',
            'isnull'    => 'true',
            'module'    => 'Contacts',
        ),

        'student_id' => array(
            'name'              => 'student_id',
            'rname'             => 'id',
            'vname'             => 'LBL_STUDENT_ID',
            'type'              => 'id',
            'table'             => 'contacts',
            'isnull'            => 'true',
            'module'            => 'Contacts',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),
        'ju_contacts' => array(
            'name'          => 'ju_contacts',
            'type'          => 'link',
            'relationship'  => 'contact_vouchers',
            'module'        => 'Contacts',
            'bean_name'     => 'Contact',
            'source'        => 'non-db',
            'vname'         => 'LBL_STUDENT_NAME',
        ),
        //Custom Relationship. Student  - Voucher (1-n)  By Lap Nguyen
        //Custom Relationship. Voucher - Sponsor  By Lap Nguyen
        'ju_sponsor'=>array(
            'name' => 'ju_sponsor',
            'type' => 'link',
            'relationship' => 'j_sponsor_vouchers',
            'module' => 'J_Sponsor',
            'bean_name' => 'J_Sponsor',
            'source' => 'non-db',
            'vname' => 'LBL_SPONSOR',
        ),
    ),
    'relationships'=>array (
            //Custom Relationship. Voucher - Sponsor  By Lap Nguyen
        'j_sponsor_vouchers' => array(
            'lhs_module'        => 'J_Voucher',
            'lhs_table'            => 'j_voucher',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_Sponsor',
            'rhs_table'            => 'j_sponsor',
            'rhs_key'            => 'voucher_id',
            'relationship_type'    => 'one-to-many',
        ),
    ),
    'optimistic_locking'=>true,
    'indices' => array (
        array('name' =>'idx_voucher_name_id', 'type'=>'index', 'fields'=>array('name','id','deleted')),
    ),
    'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('J_Voucher','J_Voucher', array('basic','team_security','assignable'));