/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({url:'rest/v10/ForecastManagerWorksheets',show:false,viewModule:{},selectedUser:{},timePeriod:'',gTable:'',isExpandableRows:'',_collection:{},fetchInProgress:false,commitLogTemplate:_.template('<article><%= text %><br><date><%= text2 %></date></article>'),commitLogLoadingTemplate:_.template('<div class="extend results"><article><%= loadingMessage %></article></div>'),dirtyModels:new Backbone.Collection(),dirtyTimeperiod:'',dirtyUser:'',draftModels:new Backbone.Collection(),draftTimeperiod:'',draftUser:'',events:{'click a[rel=historyLog] i.icon-exclamation-sign':'displayHistoryLog'},initialize:function(options){this.viewModule=app.viewModule;var self=this;app.view.View.prototype.initialize.call(this,options);this.selectedUser={id:app.user.get('id'),"isManager":app.user.get('isManager'),"showOpps":false};this.timePeriod=app.defaultSelections.timeperiod_id.id
this.ranges=app.defaultSelections.ranges.id
this._collection=this.context.forecasts.worksheetmanager;this._collection.url=this.createURL();this.totalModel=new(Backbone.Model.extend({amount:0,quota:0,best_case:0,best_adjusted:0,likely_case:0,likely_adjusted:0,worst_case:0,worst_adjusted:0}));},updateWorksheetBySelectedUser:function(selectedUser){if(this.isDirty()){this.dirtyUser=this.selectedUser;this.draftUser=this.selectedUser;}
this.selectedUser=selectedUser;if(!this.showMe()){return false;}
this.context.forecasts.worksheetmanager.url=this.createURL();this.safeFetch(true);},unbindData:function(){if(this._collection)this._collection.off(null,null,this);if(this.context.forecasts)this.context.forecasts.off(null,null,this);if(this.context.forecasts.worksheetmanager)this.context.forecasts.worksheetmanager.off(null,null,this);$(window).unbind("beforeunload");app.view.View.prototype.unbindData.call(this);},bindDataChange:function(){if(this._collection){this._collection.on("reset",function(){self.cleanUpDirtyModels();self.cleanUpDraftModels();self.render();},this);this._collection.on("change",function(model,changed){this.dirtyModels.add(model);this.context.forecasts.trigger('forecasts:worksheet:dirty',model,changed);},this);}
if(this.context.forecasts){var self=this;this.context.forecasts.on("change:selectedUser",function(context,selectedUser){this.updateWorksheetBySelectedUser(selectedUser);},this);this.context.forecasts.on("change:selectedTimePeriod",function(context,timePeriod){this.updateWorksheetBySelectedTimePeriod(timePeriod);},this);this.context.forecasts.on("change:selectedRanges",function(context,ranges){this.updateWorksheetBySelectedRanges(ranges);},this);this.context.forecasts.worksheetmanager.on("change",function(){this.calculateTotals();},this);this.context.forecasts.on("forecasts:committed:saved forecasts:worksheet:saved",function(){if(this.showMe()){this.context.forecasts.worksheetmanager.url=this.createURL();this.safeFetch();}},this);this.context.forecasts.on('forecasts:worksheet:saveWorksheet',function(isDraft){this.saveWorksheet(isDraft);},this);var worksheet=this;$(window).bind("beforeunload",function(){if(worksheet.isDirty()){return app.lang.get("LBL_WORKSHEET_SAVE_CONFIRM_UNLOAD","Forecasts");}});}},isDirty:function(){return(this.dirtyModels.length>0);},saveWorksheet:function(isDraft){var self=this,saveObj={totalToSave:0,saveCount:0,model:"",isDraft:isDraft,timeperiod:self.dirtyTimeperiod,userId:self.dirtyUser.id};if(this.showMe()){if(this.isDirty()){saveObj.totalToSave=self.dirtyModels.length;self.dirtyModels.each(function(model){saveObj.model=model;self._worksheetSaveHelper(saveObj);if(isDraft==true){self.draftModels.add(model,{merge:true});}});self.cleanUpDirtyModels();}else if(!isDraft&&self.draftModels.length>0){saveObj.totalToSave=self.draftModels.length;self.draftModels.each(function(model){saveObj.model=model;self._worksheetSaveHelper(saveObj);});self.cleanUpDirtyModels();self.cleanUpDraftModels();}else{this.context.forecasts.trigger('forecasts:worksheet:saved',saveObj.totalToSave,'mgr_worksheet',isDraft);}}
return saveObj.totalToSave},_worksheetSaveHelper:function(saveObj){var self=this;saveObj.model.set({draft:(saveObj.isDraft==true)?1:0,timeperiod_id:saveObj.timeperiod||self.timePeriod,current_user:saveObj.userId||self.selectedUser.id},{silent:true});saveObj.model.url=self.url.split("?")[0]+"/"+saveObj.model.get("id");saveObj.model.save({},{success:function(){saveObj.saveCount++;if(saveObj.totalToSave===saveObj.saveCount){self.context.forecasts.trigger('forecasts:worksheet:saved',saveObj.totalToSave,'mgr_worksheet',saveObj.isDraft);}},silent:true});},cleanUpDirtyModels:function(){this.dirtyModels.reset();this.dirtyTimeperiod='';this.dirtyUser='';},cleanUpDraftModels:function(){this.draftModels.reset();this.draftTimeperiod='';this.draftUser='';},setColumnVisibility:function(cols,value,ctx){var aoColumns=this.gTable.fnSettings().aoColumns;for(var i in cols){var columnName=cols[i];for(var k in aoColumns){if(aoColumns[k].sName==columnName){this.gTable.fnSetColumnVis(k,value==1);break;}}}},checkConfigForColumnVisibility:function(colKey){return app.forecasts.utils.getColumnVisFromKeyMap(colKey,this.name,this.context.forecasts.config);},safeFetch:function(fetch){if(this.fetchInProgress){return;}
this.fetchInProgress=true;if(_.isUndefined(fetch)){fetch=true;}
var collection=this._collection;var self=this;if(this.isDirty()){if(confirm(app.lang.get("LBL_WORKSHEET_SAVE_CONFIRM","Forecasts"))){self.context.forecasts.set({reloadCommitButton:true});var svWkFn=function(){self.context.forecasts.off('forecasts:worksheet:saved',svWkFn);collection.fetch();};self.context.forecasts.on('forecasts:worksheet:saved',svWkFn);this.saveWorksheet()}else{self.context.forecasts.set({reloadCommitButton:true});if(fetch){collection.fetch();}}}
else{if(fetch){collection.fetch();}}
this.fetchInProgress=false;},_renderField:function(field){app.view.View.prototype._renderField.call(this,field);if(field.viewName!="edit"&&field.def.clickToEdit===true&&_.isEqual(this.selectedUser.id,app.user.get('id'))){field=new app.view.ClickToEditField(field,this);}},_render:function(){var self=this;if(!this.showMe()){return false;}
$("#view-sales-rep").addClass('hide').removeClass('show');$("#view-manager").addClass('show').removeClass('hide');this.context.forecasts.set({currentWorksheet:"worksheetmanager"});app.view.View.prototype._render.call(this);var columnDefs=[];var fields=this.meta.panels[0].fields;for(var i=0;i<fields.length;i++){if(fields[i].enabled){var fieldDef={"sName":fields[i].name,"bVisible":this.checkConfigForColumnVisibility(fields[i].name)};if(!_.isUndefined(fields[i].type))
{switch(fields[i].type)
{case"int":case"currency":case"editableCurrency":fieldDef["sSortDataType"]="dom-number";fieldDef["sType"]="numeric";fieldDef["sClass"]="number";break;}
switch(fields[i].name)
{case"name":fieldDef["sWidth"]="30%";break;}}
columnDefs.push(fieldDef);}}
this.gTable=this.$el.find(".worksheetManagerTable").dataTable({"bAutoWidth":false,"aaSorting":[],"aoColumns":columnDefs,"bInfo":false,"bPaginate":false});if(this.getDraftModels().length>0){self.context.forecasts.trigger("forecasts:commitButtons:enabled");}
this.calculateTotals();self.context.forecasts.trigger('forecasts:worksheetmanager:rendered');},getDraftModels:function(){return this._collection.filter(function(model){if(model.get("version")=="0"){this.draftModels.add(model,{merge:true});return true;}
return false;},this);},displayHistoryLog:function(event){var self=this;var nTr=_.first($(event.target).parents('tr'));if(self.gTable.fnIsOpen(nTr)){self.gTable.fnClose(nTr);}else{var colspan=$(nTr).children('td').length;self.gTable.fnOpen(nTr,this.commitLogLoadingTemplate({'loadingMessage':App.lang.get("LBL_LOADING_COMMIT_HISTORY",'Forecasts')}),'details');$(nTr).next().children("td").attr("colspan",colspan);self.fetchUserCommitHistory(event,nTr);}},fetchUserCommitHistory:function(event,nTr){var jTarget=$(event.target),dataCommitDate=jTarget.data('commitdate'),options={timeperiod_id:this.timePeriod,user_id:jTarget.data('uid'),forecast_type:(jTarget.data('showopps'))?'Direct':'Rollup'};return app.api.call('read',app.api.buildURL('Forecasts','committed',null,options),null,{success:function(data){var commitDate=new Date(dataCommitDate),newestModel=new Backbone.Model(_.first(data)),otherModels=_.last(data,data.length-1),oldestModel={};for(var i=0;i<otherModels.length;i++){if(new Date(otherModels[i].date_modified)<=commitDate){oldestModel=new Backbone.Model(otherModels[i]);break;}}
outputLog=app.forecasts.utils.createHistoryLog(oldestModel,newestModel,this.context.forecasts.config);$(nTr).next().children("td").children("div").html(this.commitLogTemplate(outputLog));}},{context:this});},calculateTotals:function(){var self=this,amount=0,quota=0,best_case=0,best_adjusted=0,likely_case=0,likely_adjusted=0,worst_adjusted=0,worst_case=0,included_opp_count=0,pipeline_opp_count=0,pipeline_amount=0,closed_amount=0;if(!this.showMe()){this.context.forecasts.set({updatedManagerTotals:{'amount':amount,'quota':quota,'best_case':best_case,'best_adjusted':best_adjusted,'likely_case':likely_case,'likely_adjusted':likely_adjusted,'worst_adjusted':worst_adjusted,'worst_case':worst_case,'included_opp_count':included_opp_count}},{silent:true});return false;}
self._collection.forEach(function(model){var base_rate=parseFloat(model.get('base_rate')),mPipeline_opp_count=model.get("pipeline_opp_count"),mPipeline_amount=model.get("pipeline_amount"),mClosed_amount=model.get("closed_amount"),mOpp_count=model.get("opp_count");amount+=app.currency.convertWithRate(model.get('amount'),base_rate);quota+=app.currency.convertWithRate(model.get('quota'),base_rate);best_case+=app.currency.convertWithRate(model.get('best_case'),base_rate);best_adjusted+=app.currency.convertWithRate(model.get('best_adjusted'),base_rate);likely_case+=app.currency.convertWithRate(model.get('likely_case'),base_rate);likely_adjusted+=app.currency.convertWithRate(model.get('likely_adjusted'),base_rate);worst_case+=app.currency.convertWithRate(model.get('worst_case'),base_rate);worst_adjusted+=app.currency.convertWithRate(model.get('worst_adjusted'),base_rate);included_opp_count+=(_.isUndefined(mOpp_count))?0:parseInt(mOpp_count);pipeline_opp_count+=(_.isUndefined(mPipeline_opp_count))?0:parseInt(mPipeline_opp_count);if(!_.isUndefined(mPipeline_amount)){pipeline_amount=app.math.add(pipeline_amount,mPipeline_amount);}
if(!_.isUndefined(mClosed_amount)){closed_amount=app.math.add(closed_amount,mClosed_amount);}});self.totalModel.set({amount:amount,quota:quota,best_case:best_case,best_adjusted:best_adjusted,likely_case:likely_case,likely_adjusted:likely_adjusted,worst_case:worst_case,worst_adjusted:worst_adjusted,included_opp_count:included_opp_count,pipeline_opp_count:pipeline_opp_count,pipeline_amount:pipeline_amount,closed_amount:closed_amount});var totals={'amount':amount,'quota':quota,'best_case':best_case,'best_adjusted':best_adjusted,'likely_case':likely_case,'likely_adjusted':likely_adjusted,'worst_case':worst_case,'worst_adjusted':worst_adjusted,'included_opp_count':included_opp_count,'pipeline_opp_count':pipeline_opp_count,'pipeline_amount':pipeline_amount,'closed_amount':closed_amount};this.context.forecasts.unset("updatedManagerTotals",{silent:true});this.context.forecasts.set("updatedManagerTotals",totals);},showMe:function(){var selectedUser=(this.isDirty()&&this.dirtyUser)?this.dirtyUser:this.selectedUser;return(!selectedUser.showOpps&&selectedUser.isManager)},updateWorksheetBySelectedRanges:function(params){if(this.context.forecasts.config.get('forecast_ranges')!='show_binary'){}else{this.ranges=_.first(params);}
var model=this.context.forecasts.worksheetmanager;if(!this.showMe()){return false;}
model.url=this.createURL();this.safeFetch(true);},updateWorksheetBySelectedTimePeriod:function(params){if(this.isDirty()){this.dirtyTimeperiod=this.timePeriod;this.draftTimeperiod=this.timePeriod;}
this.timePeriod=params.id;var model=this.context.forecasts.worksheetmanager;if(!this.showMe()){return false;}
model.url=this.createURL();this.safeFetch(true);},createURL:function(){var url=this.url;var args={};if(this.timePeriod){args['timeperiod_id']=this.timePeriod;}
if(this.ranges){args['ranges']=this.ranges;}
if(this.selectedUser)
{args['user_id']=this.selectedUser.id;}
url=app.api.buildURL('ForecastManagerWorksheets','','',args);return url;},getColumnHeadings:function(dTable,onlyVisible){if(onlyVisible!==false){onlyVisible=typeof onlyVisible!=='undefined'?onlyVisible:true;}
var cols=dTable.fnSettings().aoColumns;var retColumns=[];for(var i in cols){var title=this.app.lang.get(cols[i].sTitle);if(onlyVisible){if(cols[i].bVisible){retColumns.push(title);}}else{retColumns.push(title);}}
return retColumns;},hasColumn:function(columnName){var containsColumnName=false;var cols=this.gTable.fnSettings().aoColumns;for(var i in cols){if(cols[i].sName==columnName){containsColumnName=true;break;}}
return containsColumnName;}})