<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'c_invoices_modified_user' => 
  array (
    'id' => '6164752c-6a83-edb5-9833-534825494f16',
    'relationship_name' => 'c_invoices_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Invoices',
    'rhs_table' => 'c_invoices',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_invoices_created_by' => 
  array (
    'id' => '659b7e8f-9223-5e6f-782e-53482500820a',
    'relationship_name' => 'c_invoices_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Invoices',
    'rhs_table' => 'c_invoices',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_invoices_assigned_user' => 
  array (
    'id' => '7b53e2ec-cb7e-8768-20a4-534825c6d93f',
    'relationship_name' => 'c_invoices_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Invoices',
    'rhs_table' => 'c_invoices',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_invoices_c_invoicelines_1' => 
  array (
    'id' => 'b4e32e84-941a-d9b3-c320-5348254a5fd8',
    'relationship_name' => 'c_invoices_c_invoicelines_1',
    'lhs_module' => 'C_Invoices',
    'lhs_table' => 'c_invoices',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Invoicelines',
    'rhs_table' => 'c_invoicelines',
    'rhs_key' => 'id',
    'join_table' => 'c_invoices_c_invoicelines_1_c',
    'join_key_lhs' => 'c_invoices_c_invoicelines_1c_invoices_ida',
    'join_key_rhs' => 'c_invoices_c_invoicelines_1c_invoicelines_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_invoices_c_payments_1' => 
  array (
    'id' => 'ba58945c-24aa-d945-5894-534825fde7e6',
    'relationship_name' => 'c_invoices_c_payments_1',
    'lhs_module' => 'C_Invoices',
    'lhs_table' => 'c_invoices',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Payments',
    'rhs_table' => 'c_payments',
    'rhs_key' => 'id',
    'join_table' => 'c_invoices_c_payments_1_c',
    'join_key_lhs' => 'c_invoices_c_payments_1c_invoices_ida',
    'join_key_rhs' => 'c_invoices_c_payments_1c_payments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_invoices_opportunities_1' => 
  array (
    'lhs_module' => 'C_Invoices',
    'rhs_module' => 'Opportunities',
    'relationship_type' => 'one-to-one',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'c_invoices_opportunities_1',
  ),
);