<?php

/**
 *
 * LICENSE: The contents of this file are subject to the license agreement ("License") which is included
 * in the installation package (LICENSE.txt). By installing or using this file, you have unconditionally
 * agreed to the terms and conditions of the License, and you may not use this file except in compliance
 * with the License.
 *
 * @author     Original Author Biztech Co.
 */
$dictionary['bc_survey_submission'] = array(
    'table' => 'bc_survey_submission',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'module_id' =>
        array(
            'required' => false,
            'name' => 'module_id',
            'vname' => 'LBL_MODULE_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'target_module_name' =>
        array(
            'required' => false,
            'name' => 'target_module_name',
            'vname' => 'LBL_TARGET_MODULE_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'submission_date' =>
        array(
            'required' => false,
            'name' => 'submission_date',
            'vname' => 'LBL_SUBMISSION_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'email_opened' =>
        array(
            'required' => false,
            'name' => 'email_opened',
            'vname' => 'LBL_EMAIL_OPENED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'survey_send' =>
        array(
            'required' => false,
            'name' => 'survey_send',
            'vname' => 'LBL_SURVEY_SEND',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'schedule_on' =>
        array(
            'required' => false,
            'name' => 'schedule_on',
            'vname' => 'LBL_SCHEDULE_ON',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'status' =>
        array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Mail_not_receive',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'survey_submission_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'customer_name' =>
        array(
            'required' => false,
            'name' => 'customer_name',
            'vname' => 'LBL_CUSTOMER_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
        ),
        'resubmit' =>
        array(
            'required' => false,
            'name' => 'resubmit',
            'vname' => 'LBL_RESUBMIT',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'resubmit_counter' =>
        array(
            'required' => true,
            'name' => 'resubmit_counter',
            'vname' => 'LBL_RESUBMIT_NUMBER',
            'type' => 'int',
            'len' => 11,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
        ),
        'change_request' =>
        array(
            'required' => true,
            'name' => 'change_request',
            'vname' => 'LBL_CHANGE_REQUEST',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'default' => 'N/A',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '25',
        ),
        'submitted_by' =>
        array(
            'required' => false,
            'name' => 'submitted_by',
            'vname' => 'LBL_SUBMITTED_BY',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'options' => 'submitted_by',
            'default' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'recipient_email_field' =>
        array(
            'required' => false,
            'name' => 'recipient_email_field',
            'vname' => 'LBL_CHANGE_REQUEST',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'default' => 'N/A',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
        ),
        'base_score' =>
        array(
            'required' => false,
            'name' => 'base_score',
            'vname' => 'LBL_BASE_SCORE',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '11',
            'isnull' => 'false',
        ),
        'obtain_score' =>
        array(
            'required' => false,
            'name' => 'obtain_score',
            'vname' => 'LBL_OBTAIN_SCORE',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'isnull' => 'false',
            'len' => 11,
        ),
       'score_percentage' =>
        array(
            'required' => false,
            'name' => 'score_percentage',
            'vname' => 'LBL_SCORE_PERCENTAGE',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
    ),
        'submission_type' =>
        array(
            'required' => false,
            'name' => 'submission_type',
            'vname' => 'LBL_SUBMISSION_TYPE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'submission_ip_address' =>
        array(
            'required' => false,
            'name' => 'submission_ip_address',
            'vname' => 'LBL_SUBMISSION_IP_ADDRESS',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'submitted_survey_language' =>
        array(
            'dependency' => '',
            'visibility_grid' => '',
            'required' => false,
            'name' => 'submitted_survey_language',
            'vname' => 'LBL_SUBMITTED_SURVEY_LANGUAGE',
            'type' => 'enum',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'survey_language_dom',
            'dbType' => 'enum',
            'separator' => '<br>',
    ),
        'new_record_id' =>
        array(
            'required' => false,
            'name' => 'new_record_id',
            'vname' => 'LBL_MODULE_RECORD_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
    ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('bc_survey_submission', 'bc_survey_submission', array('basic', 'assignable'));
