<?php

/**
 *
 * LICENSE: The contents of this file are subject to the license agreement ("License") which is included
 * in the installation package (LICENSE.txt). By installing or using this file, you have unconditionally
 * agreed to the terms and conditions of the License, and you may not use this file except in compliance
 * with the License.
 *
 * @author     Original Author Biztech Co.
 */

$dictionary['bc_survey_questions'] = array(
    'table' => 'bc_survey_questions',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'name' =>
        array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' =>
            array(
                'boost' => 3,
            ),
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'merge_filter' => 'disabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'size' => '20',
        ),
        'description' =>
        array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => '6',
            'cols' => '80',
            'required' => false,
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'Full text of the note',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
        ),
        'is_required' =>
        array(
            'required' => false,
            'name' => 'is_required',
            'vname' => 'LBL_IS_REQUIRED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'question_type' =>
        array(
            'required' => false,
            'name' => 'question_type',
            'vname' => 'LBL_QUESTION_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Textbox',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'question_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'question_help_comment' =>
        array(
            'name' => 'question_help_comment',
            'vname' => 'LBL_QUESTION_HELP_COMMENT',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => '6',
            'cols' => '80',
            'required' => false,
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'Full text of the note',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
        ),
        'parent_type' =>
        array(
            'required' => false,
            'name' => 'parent_type',
            'vname' => 'LBL_PARENT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'parent_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'question_sequence' =>
        array(
            'required' => false,
            'name' => 'question_sequence',
            'vname' => 'LBL_QUESTION_SEQUENCE',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '11',
            'size' => '20',
        ),
        'is_datetime' =>
        array(
            'required' => false,
            'name' => 'is_datetime',
            'vname' => 'LBL_IS_DATETIME',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'is_sort' =>
        array(
            'required' => false,
            'name' => 'is_sort',
            'vname' => 'LBL_IS_SORT',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'min' =>
        array(
            'required' => false,
            'name' => 'min',
            'vname' => 'LBL_MIN',
            'type' => 'varchar',
            'dbType' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'max' =>
        array(
            'required' => false,
            'name' => 'max',
            'vname' => 'LBL_MAX',
            'type' => 'varchar',
            'dbType' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'precision_value' =>
        array(
            'required' => false,
            'name' => 'precision_value',
            'vname' => 'LBL_PRECISION',
            'type' => 'int',
            'dbType' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'maxsize' =>
        array(
            'required' => false,
            'name' => 'maxsize',
            'vname' => 'LBL_MAXSIZE',
            'type' => 'int',
            'dbType' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'scale_slot' =>
        array(
            'required' => false,
            'name' => 'scale_slot',
            'vname' => 'LBL_SCALE_SLOT',
            'type' => 'int',
            'dbType' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'advance_type' =>
        array(
            'required' => false,
            'name' => 'advance_type',
            'vname' => 'LBL_ADVANCE_TYPE',
            'type' => 'text',
            'dbType' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 1000,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'matrix_row' =>
        array(
            'required' => false,
            'name' => 'matrix_row',
            'vname' => 'LBL_MATRIX_ROW',
            'type' => 'text',
            'dbType' => 'longblob',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'matrix_col' =>
        array(
            'required' => false,
            'name' => 'matrix_col',
            'vname' => 'LBL_MATRIX_COLUMN',
            'type' => 'text',
            'dbType' => 'longblob',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'enable_scoring' =>
        array(
            'required' => false,
            'name' => 'enable_scoring',
            'vname' => 'LBL_ENABLE_SCORE',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
    ),
        'base_weight' =>
        array(
            'required' => false,
            'name' => 'base_weight',
            'vname' => 'LBL_BASE_WEIGHT',
            'type' => 'int',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
            'len' => '11',
            'size' => '20',
        ),
       'is_skip_logic' =>
        array(
            'required' => false,
            'name' => 'is_skip_logic',
            'vname' => 'LBL_SKIP_LOGIC',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
    ),
        'enable_other_option' =>
        array(
            'required' => false,
            'name' => 'enable_other_option',
            'vname' => 'LBL_ENABLE_OTHER_OPTION',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
    ),
         'selection_limit' =>
        array(
            'required' => false,
            'name' => 'selection_limit',
            'vname' => 'LBL_SELECTION_LIMIT',
            'type' => 'int',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
            'len' => '11',
            'size' => '20',
    ),
        'desable_piping' =>
        array(
            'required' => false,
            'name' => 'desable_piping',
            'vname' => 'LBL_DESABLE_PIPING',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
    ),
        'sync_fields' =>
        array(
            'required' => false,
            'name' => 'sync_fields',
            'vname' => 'LBL_SYNC_FIELDS',
            'type' => 'varchar',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
            'len' => '255',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('bc_survey_questions', 'bc_survey_questions', array('basic', 'assignable'));
