<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['J_Feedback'] = array(
        'table'=>'j_feedback',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'status' => 
            array (
                'required' => false,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_feedback_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'feedback_time' => 
            array (
                'required' => false,
                'name' => 'feedback_time',
                'vname' => 'LBL_FEEDBACK_TIME',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'feedback_time_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'name' => 
            array (
                'name' => 'name',
                'vname' => 'LBL_NAME',
                'type' => 'name',
                'link' => true,
                'dbType' => 'varchar',
                'len' => '255',
                'unified_search' => false,
                'full_text_search' => 
                array (
                    'boost' => 3,
                ),
                'required' => true,
                'importable' => 'required',
                'duplicate_merge' => 'enabled',
                'merge_filter' => 'selected',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'duplicate_merge_dom_value' => '3',
                'audited' => true,
                'reportable' => true,
                'calculated' => false,
                'size' => '20',
            ),
            'priority' => 
            array (
                'required' => false,
                'name' => 'priority',
                'vname' => 'LBL_PRIORITY',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'priority_feedback_list',
                'studio' => 'visible',
                'dependency' => false, 
            ),
            'received_date' => 
            array (
                'required' => true,
                'name' => 'received_date',
                'vname' => 'LBL_RECEIVED_DATE ',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'display_default' => 'now',
            ),
            'resolved_date' => 
            array (
                'required' => false,
                'name' => 'resolved_date',
                'vname' => 'LBL_RESOLVED_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'ec_action' => 
            array (
                'required' => false,
                'name' => 'ec_action',
                'vname' => 'LBL_EC_ACTION',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'rows' => '4',
                'cols' => '40',
            ),
            'efl_action' => 
            array (
                'required' => false,
                'name' => 'efl_action',
                'vname' => 'LBL_EFL_ACTION',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'rows' => '4',
                'cols' => '40',
            ),
            'feedback' => 
            array (
                'required' => false,
                'name' => 'feedback',
                'vname' => 'LBL_FEEDBACK',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'rows' => '4',
                'cols' => '40',
            ),
            'plain_text' => 
            array (
                'required' => false,
                'name' => 'plain_text',
                'vname' => 'LBL_PLAIN_TEXT',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'rows' => '4',
                'cols' => '40',
            ),
            'to_assigned_to' =>
            array (
                'name' => 'to_assigned_to',
                'vname' => 'LBL_TO_ASSIGNED_TO',
                'type' => 'bool',
                'default' => '0',
            ),
            'to_other_email' =>
            array (
                'name' => 'to_other_email',
                'vname' => 'LBL_TO_OTHER_EMAIL',
                'type' => 'bool',
                'default' => '0',
            ),
            'other_email' => 
            array (
                'name' => 'other_email',
                'vname' => 'LBL_OTHER_EMAIL',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
            ),
            'type_feedback_list' => 
            array (
                'name'=> 'type_feedback_list',
                'vname' => 'LBL_TYPE_FEEDBACK_LIST',
                'type'  => 'enum',
                'options'   => 'type_feedback_list',
                'massupdate' => 0,
                'audited' => false,
                'default' => 'Internal',
            ),
            'relate_feedback_list' => 
            array (
                'name'=> 'relate_feedback_list',
                'vname' => 'LBL_RELATE_FEEDBACK_LIST',
                'type'  => 'enum',
                'options'   => 'full_relate_feedback_list',
                'len' => '150',
                'massupdate' => 0,
                'audited' => false,
                'required' => true,
            ),
            
            'slc_target' => 
            array (
                'name'=> 'slc_target',
                'vname' => 'LBL_TARGET',
                'type'  => 'enum',
                'options'   => 'jfeedback_slc_target_list',
                'massupdate' => 0,
                'audited' => false,
            ),
            'receiver_id' => 
            array (
                'required' => false,
                'name' => 'receiver_id',
                'vname' => '',
                'type' => 'id',
                'massupdate' => 0,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => true,
                'reportable' => false,
                'len' => 36,
                'size' => '20',
            ),
            'receiver' => 
            array (
                'required' => false,
                'source' => 'non-db',
                'name' => 'receiver',
                'vname' => 'LBL_RECEIVER',
                'type' => 'relate',
                'massupdate' => 0, 
                'audited' => true,
                'reportable' => true,
                'len' => '255',
                'size' => '20',
                'id_name' => 'receiver_id',
                'ext2' => 'Users',
                'module' => 'Users',
                'rname' => 'name',
                'quicksearch' => 'enabled',
                'studio' => 'visible',
            ),
            'users' => 
            array (
                'name' => 'users',
                'type' => 'link',
                'source'=>'non-db',
            ),
            'feedback_code' => 
            array (
                'required' => false,
                'name' => 'feedback_code',
                'vname' => 'LBL_FEEDBACK_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '50',
                'size' => '20',
            ),
            'is_portal' => array(
                'name' => 'is_portal',
                'type' => 'bool',
            ),
            
           // 'type' => 'A'
        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('J_Feedback','J_Feedback', array('basic','team_security','assignable'));