/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({extendsFrom:"ForecastsIndexLayout",initialize:function(options){if(_.isUndefined(options.context.forecasts)){options.context=_.extend(options.context,this.initializeAllModels(options.context));options.context.forecasts=new Backbone.Model({'saveClicked':false});var modelUrl=app.api.buildURL("Forecasts","config"),modelSync=function(method,model,options){var url=_.isFunction(model.url)?model.url():model.url;return app.api.call(method,url,model,options);};options.context.forecasts.config=this._getConfigModel(options,modelUrl,modelSync);}
app.view.Layout.prototype.initialize.call(this,options);},_getConfigModel:function(options,syncUrl,syncFunction){var SettingsModel=Backbone.Model.extend({url:syncUrl,sync:syncFunction,defaults:app.metadata.getModule('Forecasts').config});return(_.has(options.context,'forecasts')&&_.has(options.context.forecasts,'config'))?new SettingsModel($.extend(true,{},options.context.forecasts.config.attributes)):new SettingsModel();},_render:function(){app.view.Layout.prototype._render.call(this);app.alert.init();this._showModal();return this;},_showModal:function(){var self=this,isAdmin=app.user.getAcls()['Forecasts'].admin=="yes",isSetup=this.context.forecasts.config.get('is_setup');if(isAdmin){var params={title:app.lang.get("LBL_FORECASTS_CONFIG_TITLE","Forecasts")+":",span:10,before:{hide:function(){self.checkSettingsAndRedirect(isSetup,isAdmin);}},components:[{layout:(this.context.forecasts.config.get('is_setup')==1)?"tabbedConfig":"wizardConfig"}]};var callback=function(){return self.checkSettingsAndRedirect(isSetup,isAdmin)};this.trigger("modal:forecastsConfig:open",params,callback);}else{var alert=app.alert.show('no_access_error',{level:'error',messages:app.lang.get("LBL_FORECASTS_CONFIG_USER_SPLASH","Forecasts"),title:app.lang.get("LBL_FORECASTS_CONFIG_TITLE","Forecasts")+":"});alert.getCloseSelector().on('click',function(){return self.checkSettingsAndRedirect(isSetup,isAdmin);})}},checkSettingsAndRedirect:function(isSetup,isAdmin){var state={isSetup:isSetup,isAdmin:isAdmin,saveClicked:this.context.forecasts.get('saveClicked')},location=this.getRedirectURL(state),self=this;if(isAdmin&&state.saveClicked==true){app.metadata.sync();if(!isSetup){var alert=app.alert.show('forecast_opp_notice',{level:'confirmation',showCancel:false,messages:app.lang.get("LBL_FORECASTS_WIZARD_REFRESH_NOTICE","Forecasts")});alert.getCloseSelector().on('click',function(){self.displaySuccessAndReload(location);});}else{this.displaySuccessAndReload(location);}}else{window.location=location;}},getRedirectURL:function(state){if(!state.isAdmin||(state.isAdmin&&state.isSetup==0&&state.saveClicked==false)){return'index.php?module=Home';}else{return'index.php?module=Forecasts';}},displaySuccessAndReload:function(location){var alert=app.alert.show('success',{level:'success',autoClose:true,closeable:false,showCancel:false,onAutoClose:function(){window.location=location;},title:app.lang.get("LBL_FORECASTS_WIZARD_SUCCESS_TITLE","Forecasts")+":",messages:[app.lang.get("LBL_FORECASTS_WIZARD_SUCCESS_MESSAGE","Forecasts")]});alert.getCloseSelector().on('click',function(){window.location=location;});}})