/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({events:{'click #module_list li a':'onModuleTabClicked','click #createList li a':'onCreateClicked','click .typeahead a':'clearSearch','click .navbar-search .btn':'gotoFullSearchResultsPage'},initialize:function(options){app.events.on("app:sync:complete",this.render,this);app.events.on("app:logout",this.render,this);app.view.View.prototype.initialize.call(this,options);},_renderHtml:function(){var self=this,menuTemplate;if(!app.api.isAuthenticated()||app.config.appStatus=='offline'){this.$el.empty();return;}
self.setModuleInfo();self.setCreateTasksList();self.setCurrentUserName();app.view.View.prototype._renderHtml.call(self);menuTemplate=app.template.getView('dropdown-menu');this.$('.search-query').searchahead({request:self.fireSearchRequest,compiler:menuTemplate,throttleMillis:(app.config.requiredElapsed||500),throttle:function(callback,millis){if(!self.debounceFunction){self.debounceFunction=_.debounce(function(){callback();},millis||500);}
self.debounceFunction();},onEnterFn:function(hrefOrTerm,isHref){if(isHref){window.location=hrefOrTerm;}else{app.router.navigate('#search/'+hrefOrTerm,{trigger:true});}}});},fireSearchRequest:function(term){var plugin=this,mlist,params;mlist=app.metadata.getModuleNames(true).join(',');params={q:term,fields:'name, id',module_list:mlist,max_num:app.config.maxSearchQueryResult};app.api.search(params,{success:function(data){data.module_list=app.metadata.getModuleNames(true,"create");plugin.provide(data);},error:function(error){app.error.handleHttpError(error,plugin);app.logger.error("Failed to fetch search results in search ahead. "+error);}});},gotoFullSearchResultsPage:function(evt){var term;evt.preventDefault();evt.stopPropagation();term=encodeURIComponent(this.$('.search-query').val());if(term&&term.length){this.$('.search-query').searchahead('disable',1000);app.router.navigate('#search/'+term,{trigger:true});}},onModuleTabClicked:function(evt){evt.preventDefault();evt.stopPropagation();var moduleHref=this.$(evt.currentTarget).attr('href');this.$('#module_list li').removeClass('active');this.$(evt.currentTarget).parent().addClass('active');app.router.navigate(moduleHref,{trigger:true});},onCreateClicked:function(evt){var moduleHref,hashModule;moduleHref=evt.currentTarget.hash;hashModule=moduleHref.split('/')[0];this.$('#module_list li').removeClass('active');this.$('#module_list li a[href="'+hashModule+'"]').parent().addClass('active');},hide:function(){this.$el.children().hide();},show:function(){this.$el.children().show();},setCurrentUserName:function(){this.fullName=app.user.get('full_name');},setCreateTasksList:function(){var self=this,singularModules;self.createListLabels=[];try{singularModules=SUGAR.App.lang.getAppListStrings("moduleListSingular");if(singularModules){self.createListLabels=this.creatableModuleList;}}catch(e){return;}},setModuleInfo:function(){this.currentModule=this.module;this.module_list=[];var LBL_MODULE_NAME=app.lang.getAppString('LBL_MODULE_NAME');var module_list=app.metadata.getModuleNames(true,'list');_.every(module_list,function(module){if(app.lang.get('LBL_MODULE_NAME',module)!==LBL_MODULE_NAME){this.module_list.push(module);return true;}else{return false;}},this);this.creatableModuleList=_.intersection(this.module_list,app.metadata.getModuleNames(true,"create"));},clearSearch:function(evt){this.$('.search-query').val('');}})