<?php
    /*********************************************************************************
    * By installing or using this file, you are confirming on behalf of the entity
    * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
    * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
    * http://www.sugarcrm.com/master-subscription-agreement
    *
    * If Company is not bound by the MSA, then by installing or using this file
    * you are agreeing unconditionally that Company will be bound by the MSA and
    * certifying that you have authority to bind Company accordingly.
    *
    * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
    ********************************************************************************/

    $dictionary['J_Teachercontract'] = array(
        'table'=>'j_teachercontract',
        'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'no_contract' => 
            array (
                'required' => true,
                'name' => 'no_contract',
                'vname' => 'LBL_NO_CONTRACT',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '50',
                'size' => '20',
            ),
            'contract_type' => 
            array (
                'required' => true,
                'name' => 'contract_type',
                'vname' => 'LBL_CONTRACT_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'type_TeacherContract_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'status' => 
            array (
                'required' => false,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'Active',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_TeacherContract_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'contract_date' => 
            array (
                'required' => true,
                'name' => 'contract_date',
                'vname' => 'LBL_CONTRACT_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
                'validation' => array('type' => 'isbefore', 'compareto' => 'contract_until', 'blank' => false),
            ),
            'contract_until' => 
            array (
                'required' => true,
                'name' => 'contract_until',
                'vname' => 'LBL_CONTRACT_UNTIL',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'less_non_working_hours' => 
            array (
                'required' => false,
                'name' => 'less_non_working_hours',
                'vname' => 'LBL_LESS_NON_WORKING_HOURS',
                'type' => 'float',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '18',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => '2',
            ),
            'working_hours_monthly' => 
            array (
                'required' => false,
                'name' => 'working_hours_monthly',
                'vname' => 'LBL_WORKING_HOURS_MONTHLY',
                'type' => 'float',
                'massupdate' => 0,
                'default' => '72',
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '18',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => '2',
            ),
            'teach_hours' => 
            array (
                'required' => false,
                'name' => 'teach_hours',
                'vname' => 'LBL_TEACH_HOURS',
                'type' => 'float',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '18',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => '2',
            ),
            'admin_hours' => 
            array (
                'required' => false,
                'name' => 'admin_hours',
                'vname' => 'LBL_ADMIN_HOURS',
                'type' => 'float',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '18',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => '2',
            ),
            'day_off' => 
            array (
                'required' => false,
                'name' => 'day_off',
                'vname' => 'LBL_DAY_OFF',
                'type' => 'multienum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'studio' => 'visible',
                'rows' => '4',
                'cols' => '20',
                'isMultiSelect' => true,
                'options' => 'dayoff_TeacherContract_list',
            ),
        ),
        'relationships'=>array (
        ),
        'optimistic_locking'=>true,
        'unified_search'=>true,
    );
    if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
    }
    VardefManager::createVardef('J_Teachercontract','J_Teachercontract', array('basic','team_security','assignable'));