/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({activePanel:-1,totalPanels:null,panels:[],navTabs:[],breadCrumbLabels:[],events:{'click [name=close_button]':'close','click [name=done_button]':'save','click [name=next_button]':'next','click [name=start_button]':'start','click [name=previous_button]':'previous','click .breadcrumb.two li a':'breadcrumb'},initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.breadCrumbLabels=this.layout.getBreadCrumbLabels();},close:function(evt){this.layout.context.trigger("modal:close");},start:function(evt){$(evt.target).addClass('hide');this.$el.parents('div.modal-body').addClass('with-nav');this.$el.find('a[name=next_button]').toggleClass('hide show');this.$el.find('a[name=previous_button]').toggleClass('hide show');this.next(evt);},save:function(evt){if(!$(evt.target).hasClass('disabled')){$(evt.target).addClass('disabled');var self=this;this.model.set({is_setup:true,show_forecasts_commit_warnings:true});this.context.forecasts.config.set(this.model.toJSON());this.context.forecasts.set({saveClicked:true},{silent:true});this.context.forecasts.config.save({},{success:function(){var url=app.api.buildURL("Forecasts/init");app.api.call('GET',url,null,{success:function(forecastData){app.defaultSelections=forecastData.defaultSelections;app.initData=forecastData.initData;self.layout.context.trigger("modal:close");}});}});}},next:function(evt){this.handleWizardStartScreen(evt);if($(evt.target).hasClass('disabled')==false){this.handleDirectionSwitch('next');}},previous:function(evt){this.handleWizardStartScreen(evt);if($(evt.target).hasClass('disabled')==false){this.handleDirectionSwitch('previous');}},breadcrumb:function(evt){evt.preventDefault();if($(evt.target).parent().is(".active,.disabled")==false){var clickedCrumb=$(evt.target).data('index');if(clickedCrumb!=this.activePanel){this.switchPanel(clickedCrumb);this.switchNavigationTab(clickedCrumb);this.activePanel=clickedCrumb;}}},handleWizardStartScreen:function(evt){var elParent=this.$el.parent();if(elParent.find('.modal-wizard-start').hasClass('show')){elParent.find('.modal-wizard-start').toggleClass('hide show');elParent.find('.modal-navigation').toggleClass('hide show');}},handleDirectionSwitch:function(way){if(!_.isNumber(this.totalPanels)){this.panels=this.$el.parent().find('div.modal-content').not('.modal-wizard-start');;this.totalPanels=this.panels.length-1;this.navTabs=this.$el.parent().find('div.modal-navigation li');}
var nextPanel=-1;if(way=="next"){nextPanel=this.activePanel+1;}else{nextPanel=this.activePanel-1;}
if(nextPanel<0){nextPanel=0;}else if(nextPanel>this.totalPanels){nextPanel=this.totalPanels;}
this.switchPanel(nextPanel);this.switchNavigationTab(nextPanel);this.activePanel=nextPanel;},switchPanel:function(nextPanel){if(nextPanel>0&&nextPanel!=this.totalPanels){this.$el.find('[name=next_button]').removeClass('disabled');this.$el.find('[name=previous_button]').removeClass('disabled');if(this.$el.find('[name=done_button]').hasClass('show')){this.$el.find('[name=done_button]').toggleClass('hide show');}
if(this.$el.find('[name=next_button ]').hasClass('hide')){this.$el.find('[name=next_button]').toggleClass('hide show');}}else if(nextPanel==0){this.$el.find('[name=previous_button]').addClass('disabled');}else if(nextPanel==this.totalPanels){this.$el.find('[name=next_button]').toggleClass('hide show');this.$el.find('[name=done_button]').toggleClass('hide show');}
$(this.panels[this.activePanel]).toggleClass('show hide');$(this.panels[nextPanel]).toggleClass('show hide');},switchNavigationTab:function(next){$(this.navTabs[next]).removeClass('disabled');$(this.navTabs[this.activePanel]).toggleClass('active').addClass('highlight');$(this.navTabs[next]).toggleClass('active');}})