<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'c_printinglists_modified_user' => 
  array (
    'id' => 'd4a435ab-2c5c-f502-1534-5417fca44380',
    'relationship_name' => 'c_printinglists_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Printinglists',
    'rhs_table' => 'c_printinglists',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_printinglists_created_by' => 
  array (
    'id' => 'd4db19a7-d043-a4d2-5f83-5417fc99bf37',
    'relationship_name' => 'c_printinglists_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Printinglists',
    'rhs_table' => 'c_printinglists',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_printinglists_assigned_user' => 
  array (
    'id' => 'd5a33e3d-82db-3388-a148-5417fcbc581e',
    'relationship_name' => 'c_printinglists_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Printinglists',
    'rhs_table' => 'c_printinglists',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'c_printinglists_c_vouchers_1' => 
  array (
    'id' => '55627ed1-2ae2-b505-797b-5417fc0d4b26',
    'relationship_name' => 'c_printinglists_c_vouchers_1',
    'lhs_module' => 'C_Printinglists',
    'lhs_table' => 'c_printinglists',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Vouchers',
    'rhs_table' => 'c_vouchers',
    'rhs_key' => 'id',
    'join_table' => 'c_printinglists_c_vouchers_1_c',
    'join_key_lhs' => 'c_printinglists_c_vouchers_1c_printinglists_ida',
    'join_key_rhs' => 'c_printinglists_c_vouchers_1c_vouchers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_printinglists_c_memberships_1' => 
  array (
    'rhs_label' => 'Memberships',
    'lhs_label' => 'Printinglists',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'C_Printinglists',
    'rhs_module' => 'C_Memberships',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'c_printinglists_c_memberships_1',
  ),
);