/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
(function(app){if(!_.has(app,'forecasts')){app.forecasts={}}
app.forecasts.utils={createHistoryLog:function(oldestModel,newestModel,config){var is_first_commit=false;if(_.isEmpty(oldestModel)){oldestModel=new Backbone.Model({best_case:0,likely_case:0,worst_case:0,date_entered:''})
is_first_commit=true;}
var best_difference=this.getDifference(oldestModel,newestModel,'best_case'),best_direction=this.getDirection(best_difference),likely_difference=this.getDifference(oldestModel,newestModel,'likely_case'),likely_direction=this.getDirection(likely_difference),worst_difference=this.getDifference(oldestModel,newestModel,'worst_case'),worst_direction=this.getDirection(worst_difference),args=[],text='LBL_COMMITTED_HISTORY_NONE_CHANGED',best_arrow=this.getArrowDirectionSpan(best_direction),likely_arrow=this.getArrowDirectionSpan(likely_direction),worst_arrow=this.getArrowDirectionSpan(worst_direction),num_shown=0,hb=Handlebars.compile("{{str_format key module args}}"),lang_string_key='',final_args=[],labels=[],setup_or_updated_lang_key=(is_first_commit)?'_SETUP':'_UPDATED',likely_args={changed:likely_difference!=0,show:config.get("show_worksheet_likely")},best_args={changed:best_difference!=0,show:config.get("show_worksheet_best")},worst_args={changed:worst_difference!=0,show:config.get("show_worksheet_worst")};likely_args.show?num_shown++:'';best_args.show?num_shown++:'';worst_args.show?num_shown++:'';lang_string_key='LBL_COMMITTED_HISTORY_'+num_shown+'_SHOWN';if(likely_args.changed&&likely_args.show){final_args.push(this.gatherLangArgsByParams(likely_direction,likely_arrow,likely_difference,newestModel,'likely_case'));}else if(likely_args.show){final_args.push([]);}
if(best_args.changed&&best_args.show){final_args.push(this.gatherLangArgsByParams(best_direction,best_arrow,best_difference,newestModel,'best_case'));}else if(best_args.show){final_args.push([]);}
if(worst_args.changed&&worst_args.show){final_args.push(this.gatherLangArgsByParams(worst_direction,worst_arrow,worst_difference,newestModel,'worst_case'));}else if(worst_args.show){final_args.push([]);}
labels=this.getCommittedHistoryLabel(best_args,likely_args,worst_args,is_first_commit);final_args=this.parseArgsAndLabels(final_args,labels);var text=hb({'key':lang_string_key,'module':'Forecasts','args':final_args});var oldestDateEntered=oldestModel.get('date_entered');var newestModelDate=new Date(Date.parse(newestModel.get('date_entered'))),text2='',newestModelDisplayDate=app.date.format(newestModelDate,app.user.getPreference('datepref')+' '+app.user.getPreference('timepref'));if(!_.isEmpty(oldestDateEntered)){var oldestModelDate=new Date(Date.parse(oldestDateEntered)),yearDiff=oldestModelDate.getYear()-newestModelDate.getYear(),monthsDiff=oldestModelDate.getMonth()-newestModelDate.getMonth();if(yearDiff==0&&monthsDiff<2)
{args=[newestModelDisplayDate];text2=hb({'key':'LBL_COMMITTED_THIS_MONTH','module':'Forecasts','args':args});}else{args=[monthsDiff,newestModelDisplayDate];text2=hb({'key':'LBL_COMMITTED_MONTHS_AGO','module':'Forecasts','args':args});}}else{args=[newestModelDisplayDate];text2=hb({'key':'LBL_COMMITTED_THIS_MONTH','module':'Forecasts','args':args});}
return{'text':new Handlebars.SafeString(text),'text2':new Handlebars.SafeString(text2)};},gatherLangArgsByParams:function(dir,arrow,diff,model,attrStr){var args=[];args.push(app.lang.get(dir,'Forecasts')+arrow);args.push(app.currency.formatAmountLocale(Math.abs(diff)));args.push(app.currency.formatAmountLocale(model.get(attrStr)));return args;},getArrowDirectionSpan:function(directionClass){return directionClass=="LBL_UP"?'&nbsp;<span class="icon-arrow-up font-green"></span>':directionClass=="LBL_DOWN"?'&nbsp;<span class="icon-arrow-down font-red"></span>':'';},getCommittedHistoryLabel:function(best,likely,worst,is_first_commit){var args=[];if(is_first_commit){args.push('LBL_COMMITTED_HISTORY_SETUP_FORECAST');}else{args.push('LBL_COMMITTED_HISTORY_UPDATED_FORECAST');}
if(likely.show){if(likely.changed){args.push('LBL_COMMITTED_HISTORY_LIKELY_CHANGED');}else{args.push('LBL_COMMITTED_HISTORY_LIKELY_SAME');}}
if(best.show){if(best.changed){args.push('LBL_COMMITTED_HISTORY_BEST_CHANGED');}else{args.push('LBL_COMMITTED_HISTORY_BEST_SAME');}}
if(worst.show){if(worst.changed){args.push('LBL_COMMITTED_HISTORY_WORST_CHANGED');}else{args.push('LBL_COMMITTED_HISTORY_WORST_SAME');}}
return args;},parseArgsAndLabels:function(argsArray,labels){var retArgs=[],hb=Handlebars.compile("{{str_format key module args}}");if((argsArray.length+1)!=labels.length){app.logger.error('ForecastsUtils.parseArgsAndLabels() :: argsArray and labels params are not the same length ');return null;}
retArgs.push(hb({'key':_.first(labels),'module':'Forecasts','args':[]}));labels=_.last(labels,labels.length-1);_.each(labels,function(label,index){retArgs.push(hb({'key':label,'module':'Forecasts','args':argsArray[index]}))});return retArgs;},getDifference:function(oldModel,newModel,attr){return newModel.get(attr)-oldModel.get(attr);},getDirection:function(difference){return difference>0?'LBL_UP':(difference<0?'LBL_DOWN':'');},_tableColumnsConfigKeyMapManager:{'likely_case':'show_worksheet_likely','likely_adjusted':'show_worksheet_likely','best_case':'show_worksheet_best','best_adjusted':'show_worksheet_best','worst_case':'show_worksheet_worst','worst_adjusted':'show_worksheet_worst'},_tableColumnsConfigKeyMapRep:{'likely_case':'show_worksheet_likely','best_case':'show_worksheet_best','worst_case':'show_worksheet_worst'},getColumnVisFromKeyMap:function(key,viewName,configCtx){var moduleMap={'forecastsWorksheet':'rep','forecastsWorksheetTotals':'rep','forecastsWorksheetManager':'mgr','forecastsWorksheetManagerTotals':'mgr'}
var whichKeyMap=moduleMap[viewName];var keyMap=(whichKeyMap==='rep')?this._tableColumnsConfigKeyMapRep:this._tableColumnsConfigKeyMapManager;var returnValue=configCtx.get(keyMap[key]);if(!_.isUndefined(returnValue)){returnValue=returnValue==1}else{returnValue=true;}
return returnValue;}};})(SUGAR.App);