/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({values:new Backbone.Model(),url:'rest/v10/Forecasts/chart',chart:null,chartRendered:false,chartDataSet:[],chartGroupByOptions:[],defaultDataset:'',defaultGroupBy:'',chartTitle:'',timeperiod_label:'',stopRender:false,events:{'click #forecastsChartDisplayOptions div.datasetOptions label.radio':'changeDisplayOptions','click #forecastsChartDisplayOptions div.groupByOptions label.radio':'changeGroupByOptions'},initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.values.clear({silent:true});},changeDisplayOptions:function(evt){evt.preventDefault();this.handleRenderOptions({dataset:this.handleOptionChange(evt)})},changeGroupByOptions:function(evt){evt.preventDefault();this.handleRenderOptions({group_by:_.first(this.handleOptionChange(evt))});},handleOptionChange:function(evt){el=$(evt.currentTarget);pel=el.parents('div:first');pel.find('label.checked').removeClass('checked');el.addClass('checked');return[el.attr('data-set')];},getCheckedOptions:function(divClass){var chkOptions=this.$el.find("div."+divClass+" label.checked");var options=[];_.each(chkOptions,function(o){options.push($(o).attr('data-set'));});return options;},_renderHtml:function(ctx,options){this.timeperiod_label=app.defaultSelections.timeperiod_id.label;this.chartDataSet=this.getChartDatasets();this.chartGroupByOptions=app.metadata.getStrings('app_list_strings').forecasts_chart_options_group||[];this.defaultDataset=app.defaultSelections.dataset;this.defaultGroupBy=app.defaultSelections.group_by;if(_.isUndefined(this.chartDataSet[this.defaultDataset])){this.defaultDataset=_.first(_.keys(this.chartDataSet));}
app.view.View.prototype._renderHtml.call(this,ctx,options);var values={user_id:app.user.get('id'),display_manager:app.user.get('isManager'),timeperiod_id:app.defaultSelections.timeperiod_id.id,group_by:_.first(this.getCheckedOptions('groupByOptions')),dataset:this.getCheckedOptions('datasetOptions'),ranges:app.defaultSelections.ranges};this.handleRenderOptions(values);},_render:function(){app.view.View.prototype._render.call(this);this.toggleRepOptionsVisibility();},toggleRepOptionsVisibility:function(){if(this.values.get('display_manager')===true){this.$el.find('div.groupByOptions').hide();}else{this.$el.find('div.groupByOptions').show();}},unbindData:function(){if(this.context.forecasts.worksheet)this.context.forecasts.worksheet.off(null,null,this);if(this.context.forecasts.worksheetmanager)this.context.forecasts.worksheetmanager.off(null,null,this);if(this.context.forecasts)this.context.forecasts.off(null,null,this);if(this.values)this.values.off(null,null,this);app.view.View.prototype.unbindData.call(this);},bindDataChange:function(){var self=this;this.context.forecasts.on("forecasts:committed:saved",function(){self.renderChart();});this.context.forecasts.on("forecasts:worksheet:saved",function(totalSaved,worksheet,isDraft){if(totalSaved>0&&isDraft==true){self.renderChart();}});this.context.forecasts.on('change:selectedUser',function(context,user){if(!_.isEmpty(self.chart)){self.handleRenderOptions({user_id:user.id,display_manager:(user.showOpps===false&&user.isManager===true)});self.toggleRepOptionsVisibility();}});this.context.forecasts.on('change:selectedTimePeriod',function(context,timePeriod){if(!_.isEmpty(self.chart)){self.timeperiod_label=timePeriod.label;self.handleRenderOptions({timeperiod_id:timePeriod.id});}});this.context.forecasts.on('change:selectedGroupBy',function(context,groupBy){if(!_.isEmpty(self.chart)){self.handleRenderOptions({group_by:groupBy});}});this.context.forecasts.on('change:selectedRanges',function(context,value){if(!_.isEmpty(self.chart)){self.handleRenderOptions({ranges:value});}});this.context.forecasts.on('change:hiddenSidebar',function(context,value){self.stopRender=value;if(value==false){self.renderChart();}});this.values.on('change',function(context,value){if(!_.isEmpty(value.changes)){self.renderChart();}});},handleRenderOptions:function(options){this.values.set(options);},renderChart:function(){this._initializeChart();},getChartDatasets:function(){var self=this;var ds=app.metadata.getStrings('app_list_strings').forecasts_chart_options_dataset||[];cfg=this.context.forecasts.config;cfg_key='show_worksheet_';var returnDs={};_.each(ds,function(value,key){if(cfg.get(cfg_key+key)==1){returnDs[key]=value}},self);return returnDs;},_initializeChart:function(){if(this.stopRender){return{};}
var chart,chartId="db620e51-8350-c596-06d1-4f866bfcfd5b",css={"gridLineColor":"#cccccc","font-family":"Arial","color":"#000000"},chartConfig={"orientation":"vertical","barType":this.values.get('display_manager')?"grouped":"stacked","tip":"name","chartType":"barChart","imageExportType":"png","showNodeLabels":false,"showAggregates":false,"saveImageTo":"","dataPointSize":"5"};var oldChart=$("#"+chartId+"-canvaswidget");if(!_.isEmpty(oldChart)){oldChart.remove();}
SUGAR.charts=$.extend(SUGAR.charts,{get:function(url,params,success)
{var data={r:new Date().getTime()};data=$.extend(data,params);url=app.api.buildURL('Forecasts','chart','',data);app.api.call('read',url,data,{success:success});}});if(this.values.get('display_manager')===true){this.values.set({ranges:'include'},{silent:true});}
var hb=Handlebars.compile("{{str_format key module args}}");var text=hb({'key':"LBL_CHART_FORECAST_FOR",'module':'Forecasts','args':this.timeperiod_label});this.$el.find('h4').html(text);var params=this.values.toJSON()||{};params.contentEl='chart';params.minColumnWidth=120;chart=new loadSugarChart(chartId,this.url,css,chartConfig,params,_.bind(function(chart){this.chart=chart;},this));this.chartRendered=true;}})