<?php
/*********************************************************************************
* By installing or using this file, you are confirming on behalf of the entity
* subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
* the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
* http://www.sugarcrm.com/master-subscription-agreement
*
* If Company is not bound by the MSA, then by installing or using this file
* you are agreeing unconditionally that Company will be bound by the MSA and
* certifying that you have authority to bind Company accordingly.
*
* Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
********************************************************************************/

$dictionary['J_PTResult'] = array(
    'table'=>'j_ptresult',
    'audited'=>true,
    'duplicate_merge'=>true,
    'fields'=>array (
        'pt_order' =>
        array (
            'required' => false,
            'name' => 'pt_order',
            'vname' => 'LBL_PT_ORDER',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '50',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,
        ),
        'result_koc' =>
        array (
            'required' => true,
            'name' => 'result_koc',
            'vname' => 'LBL_RESULT_KOC',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'kind_of_course_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'result_lvl' =>
        array (
            'required' => true,
            'name' => 'result_lvl',
            'vname' => 'LBL_RESULT_LVL',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'level_program_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'time_start' =>
        array (
            'required' => false,
            'name' => 'time_start',
            'vname' => 'LBL_TIME_START',
            'type' => 'datetimecombo',
            'massupdate' => '1',
            'comments' => 'comment',
            'help' => 'help',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => true,
            'reportable' => true,
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'time_end' =>
        array (
            'required' => false,
            'name' => 'time_end',
            'vname' => 'LBL_TIME_END',
            'type' => 'datetimecombo',
            'massupdate' => '1',
            'comments' => 'comment',
            'help' => 'help',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => true,
            'reportable' => true,
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'listening' =>
        array (
            'required' => false,
            'name' => 'listening',
            'vname' => 'LBL_LISTENING',
            'type' => 'decimal',
            'audited' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'speaking' =>
        array (
            'required' => false,
            'name' => 'speaking',
            'vname' => 'LBL_SPEAKING',
            'type' => 'decimal',
            'audited' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'reading' =>
        array (
            'required' => false,
            'name' => 'reading',
            'vname' => 'LBL_READING',
            'type' => 'decimal',
            'audited' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'writing' =>
        array (
            'required' => false,
            'name' => 'writing',
            'vname' => 'LBL_WRITING',
            'type' => 'decimal',
            'audited' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'result' =>
        array (
            'required' => false,
            'name' => 'result',
            'vname' => 'LBL_RESULT',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '255',
            'size' => '20',
        ),
        'score' =>
        array (
            'required' => false,
            'name' => 'score',
            'vname' => 'LBL_SCORE',
            'type' => 'decimal',
            'audited' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'lead_source' => array(
            'name' => 'lead_source',
            'vname' => 'LBL_SOURCE',
            'type' => 'enum',
            'len' => 100,
            'options' => 'lead_source_list',
        ),
        'attended' =>
        array (
            'required' => false,
            'name' => 'attended',
            'vname' => 'LBL_ATTENDED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '255',
            'size' => '20',
        ),
        'ec_note' =>
        array (
            'required' => false,
            'name' => 'ec_note',
            'vname' => 'LBL_EC_NOTE',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'rows' => '3',
            'cols' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,
        ),
        'teacher_comment' =>
        array (
            'required' => false,
            'name' => 'teacher_comment',
            'vname' => 'LBL_TEACHER_COMMENT',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'rows' => '3',
            'cols' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,
        ),
        'parent' =>
        array (
            'required' => false,
            'name' => 'parent',
            'vname' => 'LBL_PARENT',
            'type' => 'enum',
            'options' => 'ptresult_student_options',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '100',
            'size' => '20',
        ),
        'type_result' =>
        array (
            'required' => false,
            'name' => 'type_result',
            'vname' => 'LBL_TYPE_RESULT',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '100',
            'size' => '20',
        ),
        'taken_date' =>
        array (
            'name' => 'taken_date',
            'vname' => 'LBL_TAKEN_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'student_id' => array(
            'name' => 'student_id',
            'vname' => 'LBL_STUDENT_ID',
            'type' => 'id',
        ),
        'student_name' => array(
            'name' => 'student_name',
            'vname' => 'LBL_STUDENT_NAME',
            'type' => 'varchar',
            'len' => 100,
        ),
        'last_name' => array(
            'name' => 'last_name',
            'vname' => 'LBL_LAST_NAME',
            'type' => 'varchar',
            'len' => 50,
        ),
        'first_name' => array(
            'name' => 'first_name',
            'vname' => 'LBL_FIRST_NAME',
            'type' => 'varchar',
            'len' => 50,
        ),
        'student_mobile' => array(
            'name' => 'student_mobile',
            'vname' => 'LBL_STUDENT_MOBILE',
            'type' => 'phone',
            'dbType' => 'varchar',
            'len' => 100,
        ),
        'student_email' => array(
            'name' => 'student_email',
            'vname' => 'LBL_STUDENT_EMAIL',
            'type' => 'varchar',
            'len' => 50,
        ),
        'parent_name' => array(
            'name' => 'parent_name',
            'vname' => 'LBL_PARENT_NAME',
            'type' => 'varchar',
            'len' => 100,
        ),
        'student_birthdate' => array(
            'name' => 'student_birthdate',
            'vname' => 'LBL_STUDENT_BIRTHDATE',
            'type' => 'date',
        ),
        'student_gender' => array(
            'name' => 'student_gender',
            'vname' => 'LBL_STUDENT_GENDER',
            'type' => 'enum',
            'len' => 20,
            'options' => 'gender_lead_list',
        ),
        'student_status' => array(
            'name' => 'student_status',
            'vname' => 'LBL_STUDENT_STATUS',
            'type' => 'varchar',
            'len' => 50,
        ),
        // ******** TASK IMPORT ***********************
        'subject_pt' =>
        array (
            'required' => false,
            'name' => 'subject_pt',
            'vname' => 'LBL_SUBJECT_PT',
            'type' => 'varchar',
            'len' => '255',
            'source' => 'non-db',
        ),
        'aims_id_pt' =>
        array (
            'required' => false,
            'name' => 'aims_id_pt',
            'vname' => 'LBL_AIMS_ID_PT',
            'type' => 'varchar',
            'len' => '255',
            'source' => 'non-db',
        ),
        'description_pt' =>
        array (
            'required' => false,
            'name' => 'description_pt',
            'vname' => 'LBL_DESCRIPTION_PT',
            'type' => 'varchar',
            'len' => '255',
            'source' => 'non-db',
        ),
         'student_aims_id' =>
        array (
            'required' => true,
            'name' => 'student_aims_id',
            'vname' => 'LBL_STUDENT_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'AIMS ID Int',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        //***************** END: TASK IMPORT
    ),
    'relationships'=>array (
    ),
    'optimistic_locking'=>true,
    'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('J_PTResult','J_PTResult', array('basic','team_security','assignable'));