<?php
/*********************************************************************************
* By installing or using this file, you are confirming on behalf of the entity
* subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
* the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
* http://www.sugarcrm.com/master-subscription-agreement
*
* If Company is not bound by the MSA, then by installing or using this file
* you are agreeing unconditionally that Company will be bound by the MSA and
* certifying that you have authority to bind Company accordingly.
*
* Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
********************************************************************************/

$dictionary['J_Payment'] = array(
    'table'=>'j_payment',
    'audited'=>true,
    'duplicate_merge'=>true,
    'fields'=>array (
        'status_paid' =>
        array (
            'required' => false,
            'name' => 'status_paid',
            'vname' => 'LBL_STATUS_PAID',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Unpaid',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'status_paid_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'payment_type' =>
        array (
            'required' => false,
            'name' => 'payment_type',
            'vname' => 'LBL_PAYMENT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'payment_type_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'payment_date' =>
        array (
            'required' => true,
            'name' => 'payment_date',
            'vname' => 'LBL_PAYMENT_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Date',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'settle_date' =>
        array (
            'required' => true,
            'name' => 'settle_date',
            'vname' => 'LBL_SETTLE_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Settle Date',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'number_of_skill' =>
        array (
            'required' => false,
            'name' => 'number_of_skill',
            'vname' => 'LBL_NUMBER_OF_SKILL',
            'type' => 'int',
            'len' => 10,
            'size' => '5',
        ),
        'number_of_connect' =>
        array(
            'required' => false,
            'name' => 'number_of_connect',
            'vname' => 'LBL_NUMBER_OF_CONNECT',
            'type' => 'int',
            'len' => 10,
            'size' => '5',
        ),
        'number_of_practice' =>
        array(
            'required' => false,
            'name' => 'number_of_practice',
            'vname' => 'LBL_NUMBER_OF_PRACTICE',
            'type' => 'int',
            'len' => 10,
            'size' => '5',
        ),
        'card_type' =>
        array (
            'required' => false,
            'name' => 'card_type',
            'vname' => 'LBL_CARD_TYPE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '50',
            'size' => '20',
            'source' => 'non-db',
        ),
        'number_of_payment' => array(
            'name' => 'number_of_payment',
            'vname' => 'LBL_NUMBER_OF_PAYMENT',
            'type' => 'enum',
            'len' => 10,
            'size' => '20',
            'options' => 'number_of_payment_junior_list',
        ),
        'moving_tran_out_date' =>
        array (
            'required' => true,
            'name' => 'moving_tran_out_date',
            'vname' => 'LBL_MOVING_TRANSFER_OUT_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Date',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'moving_tran_in_date' =>
        array (
            'required' => true,
            'name' => 'moving_tran_in_date',
            'vname' => 'LBL_MOVING_TRANSFER_IN_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Date',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'number_class' =>
        array (
            'required' => false,
            'name' => 'number_class',
            'vname' => 'LBL_NUMBER_CLASS',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Number Class',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'disable_num_format' => '',
            'min' => false,
            'max' => false,
        ),
        'sale_type' =>
        array (
            'required' => false,
            'name' => 'sale_type',
            'vname' => 'LBL_SALE_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Not set',
            'no_default' => false,
            'comments' => '',
            'help' => 'Sale Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'sale_type_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'start_study' =>
        array (
            'required' => true,
            'name' => 'start_study',
            'vname' => 'LBL_START_STUDY',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Start Study',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'end_study' =>
        array (
            'required' => true,
            'name' => 'end_study',
            'vname' => 'LBL_END_STUDY',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'End Study',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'class_start' =>
        array (
            'required' => false,
            'name' => 'class_start',
            'vname' => 'LBL_CLASS_START',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Start Class',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'class_end' =>
        array (
            'required' => false,
            'name' => 'class_end',
            'vname' => 'LBL_CLASS_END',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Start Class',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'sessions' =>
        array (
            'required' => false,
            'name' => 'sessions',
            'vname' => 'LBL_SESSIONS',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'default' => '',
            'comments' => '',
            'help' => 'Sessions',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '4',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,
        ),
        'tuition_fee' =>
        array (
            'required' => false,
            'name' => 'tuition_fee',
            'vname' => 'LBL_TUITION_FEE',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Tuition Fee',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
            'default' => '',
        ),
        'currency_id' =>
        array (
            'required' => false,
            'name' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'type' => 'currency_id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 36,
            'size' => '20',
            'dbType' => 'id',
            'studio' => 'visible',
            'function' =>
            array (
                'name' => 'getCurrencyDropDown',
                'returns' => 'html',
            ),
        ),
        'paid_amount' =>
        array (
            'required' => false,
            'name' => 'paid_amount',
            'vname' => 'LBL_PAID_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'amount_bef_discount' =>
        array (
            'required' => false,
            'name' => 'amount_bef_discount',
            'vname' => 'LBL_AMOUNT_BEF_DISCOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Amount Before Discount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'discount_amount' =>
        array (
            'required' => false,
            'name' => 'discount_amount',
            'vname' => 'LBL_DISCOUNT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Discount Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'remaining_freebalace' =>
        array (
            'required' => false,
            'name' => 'remaining_freebalace',
            'vname' => 'LBL_REMAINING_FREEBALANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Discount Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'discount_percent' =>
        array (
            'required' => false,
            'name' => 'discount_percent',
            'vname' => 'LBL_DISCOUNT_PERCENT',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Discount Percent',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '6',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
            'default' => '',
        ),
        'aims_wrong_amount' =>
        array (
            'required' => false,
            'name' => 'aims_wrong_amount',
            'vname' => 'AIMS Wrong Amount',
            'type' => 'decimal',
            'audited' => false,
            'len' => '13',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'aims_wrong_hour' =>
        array (
            'required' => false,
            'name' => 'aims_wrong_hour',
            'vname' => 'AIMS Wrong Hour',
            'type' => 'decimal',
            'audited' => false,
            'len' => '13',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ),
        'aims_wrong_date' =>
        array (
            'required' => true,
            'name' => 'aims_wrong_date',
            'vname' => 'AIMS Wrong Date',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'ratio' =>
        array (
            'required' => false,
            'name' => 'ratio',
            'vname' => 'LBL_RATIO',
            'type' => 'decimal',
            'massupdate' => 0,
            'default' => 'Not set',
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '9',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '3',
            'default' => '',
        ),

        'sub_discount_amount' =>
        array (
            'required' => false,
            'name' => 'sub_discount_amount',
            'vname' => 'LBL_SUB_DISCOUNT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
            'default' => '',
        ),
        'sub_discount_percent' =>
        array (
            'required' => false,
            'name' => 'sub_discount_percent',
            'vname' => 'LBL_SUB_DISCOUNT_PERCENT',
            'type' => 'decimal',
            'len' => '6',
            'precision' => '2',
        ),

        'total_after_discount' =>
        array (
            'required' => false,
            'name' => 'total_after_discount',
            'vname' => 'LBL_TOTAL_AFTER_DISCOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Total After Discount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'deposit_amount' =>
        array (
            'required' => false,
            'name' => 'deposit_amount',
            'vname' => 'LBL_DEPOSIT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Deposit Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'payment_amount' =>
        array (
            'required' => false,
            'name' => 'payment_amount',
            'vname' => 'LBL_GRAND_TOTAL',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'min' => 1,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 2,
            'default' => '',
        ),
        'total_amount' =>
        array (
            'required' => false,
            'name' => 'total_amount',
            'vname' => 'LBL_TOTAL_AMOUNT',
            'type' => 'currency',
            'source' => 'non-db',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
        ),
        'total_hours_adult' =>
        array (
            'required' => false,
            'name' => 'total_hours_adult',
            'vname' => 'LBL_TUITION_HOURS_ADULT',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'tuition_hours' =>
        array (
            'required' => false,
            'name' => 'tuition_hours',
            'vname' => 'LBL_TUITION_HOURS',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'paid_hours' =>
        array (
            'required' => false,
            'name' => 'paid_hours',
            'vname' => 'LBL_PAID_HOURS',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'total_hours' =>
        array (
            'required' => false,
            'name' => 'total_hours',
            'vname' => 'LBL_TOTAL_HOURS',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'payment_expired' =>
        array (
            'required' => false,
            'name' => 'payment_expired',
            'vname' => 'LBL_PAYMENT_EXPIRED',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Expired',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'loyalty' =>
        array (
            'required' => false,
            'name' => 'loyalty',
            'vname' => 'LBL_LOYALTY',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Loyalty',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '50',
            'size' => '20',
        ),
        'class_string' =>
        array (
            'required' => false,
            'name' => 'class_string',
            'vname' => 'LBL_CLASS_STRING',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '150',
            'size' => '20',
        ),
        'level_string' =>
        array (
            'required' => false,
            'name' => 'level_string',
            'vname' => 'LBL_LEVEL_STRING',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '30',
            'size' => '20',
        ),
        'kind_of_course_string' =>
        array (
            'required' => false,
            'name' => 'kind_of_course_string',
            'vname' => 'LBL_KIND_OF_COURSE_STRING',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '100',
            'size' => '20',
        ),
        'foc_type' =>
        array (
            'required' => false,
            'name' => 'foc_type',
            'vname' => 'LBL_FOC_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 30,
            'size' => '20',
            'options' => 'foc_type_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'final_sponsor' =>
        array (
            'required' => false,
            'name' => 'final_sponsor',
            'vname' => 'LBL_FINAL_SPONSOR',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Final Sponsor',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
            'default' => '',
        ),
        'final_sponsor_percent' =>
        array (
            'required' => false,
            'name' => 'final_sponsor_percent',
            'vname' => 'LBL_FINAL_SPONSOR_PERCENT',
            'type' => 'decimal',
            'len' => '6',
            'precision' => '2',
        ),
        'loyalty_amount' =>
        array (
            'required' => false,
            'name' => 'loyalty_amount',
            'vname' => 'LBL_LOYALTY_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Loyalty Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
            'default' => '',
        ),
        'loyalty_percent' =>
        array (
            'required' => false,
            'name' => 'loyalty_percent',
            'vname' => 'LBL_LOYALTY_PERCENT',
            'type' => 'decimal',
            'len' => '6',
            'precision' => '2',
        ),
        'payment_method' =>
        array (
            'required' => false,
            'name' => 'payment_method',
            'vname' => 'LBL_PAYMENT_METHOD',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Cash',
            'no_default' => false,
            'comments' => '',
            'help' => 'Payment Method',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 50,
            'size' => '20',
            'options' => 'payment_method_junior_list',
            'studio' => 'visible',
            'dependency' => false,
            'source' => 'non-db',
        ),
        'company_name' => array (
            'required' => false,
            'name' => 'company_name',
            'vname' => 'LBL_COMPANY_NAME',
            'type' => 'varchar',
            'len' => '150',
            'reportable' => true,
        ),
        'tax_code' => array (
            'required' => false,
            'name' => 'tax_code',
            'vname' => 'LBL_TAX_CODE',
            'type' => 'varchar',
            'len' => '50',
            'reportable' => true,
        ),
        'company_address' => array (
            'required' => false,
            'name' => 'company_address',
            'vname' => 'LBL_COMPANY_ADDRESS',
            'type' => 'varchar',
            'len' => '200',
            'reportable' => true,
        ),
        'used_hours' =>
        array (
            'required' => false,
            'name' => 'used_hours',
            'vname' => 'LBL_USED_HOURS',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
        ),
        'remain_hours' =>
        array (
            'required' => false,
            'name' => 'remain_hours',
            'vname' => 'LBL_REMAIN_HOURS',
            'type' => 'decimal',
            'len' => '13',
            'precision' => '2',
            'default' => '0',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'used_amount' =>
        array (
            'required' => false,
            'name' => 'used_amount',
            'vname' => 'LBL_USED_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => 'Used Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
            'default' => '',
        ),
        'remain_amount' =>
        array (
            'required' => false,
            'name' => 'remain_amount',
            'vname' => 'LBL_REMAIN_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Remain Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 13,
            'size' => '20',
            'precision' => 2,
            'default' => '',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'payment_list' =>
        array (
            'name' => 'payment_list',
            'vname' => 'LBL_CONTENT',
            'type' => 'text',
        ),
        'note' =>
        array (
            'name' => 'note',
            'vname' => 'LBL_NOTE',
            'type' => 'varchar',
            'len' => 200,
        ),
        'outstanding_list' =>
        array (
            'name' => 'outstanding_list',
            'vname' => 'LBL_CONTENT',
            'type' => 'text',
        ),
        'content' =>
        array (
            'name' => 'content',
            'vname' => 'LBL_CONTENT',
            'type' => 'text',
        ),
        'do_not_drop_revenue' =>
        array (
            'name' => 'do_not_drop_revenue',
            'vname' => 'LBL_DO_NOT_DROP_REVENUE',
            'type' => 'bool',
            'default' => '0',
        ),
        'charge_book' =>
        array (
            'name' => 'charge_book',
            'vname' => 'LBL_CHARGE_BOOK',
            'type' => 'bool',
            'default' => '1',
        ),
        'is_corporate' =>
        array (
            'name' => 'is_corporate',
            'vname' => 'LBL_IS_CORPORATE',
            'type' => 'bool',
            'default' => '0',
        ),
        'is_outstanding' =>
        array (
            'name' => 'is_outstanding',
            'vname' => 'LBL_IS_OUTSTANDING',
            'type' => 'bool',
            'default' => '0',
        ),
        'is_outing' =>
        array (
            'name' => 'is_outing',
            'vname' => 'LBL_IS_OUTING',
            'type' => 'bool',
            'default' => '0',
        ),
        'related_payment_detail' =>
        array (
            'required' => false,
            'name' => 'related_payment_detail',
            'vname' => 'LBL_RELATED_PAYMENT_DETAIL',
            'type' => 'varchar',
            'len' => 5,
            'size' => '20',
            'source' => 'non-db',
        ),
        'status' =>
        array (
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Success',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'payment_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        //Relate field with team
        'move_to_center_id' =>  array (
            'required' => false,
            'name' => 'move_to_center_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => false,
            'len' => 36,
        ),

        'move_to_center_name' =>  array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'move_to_center_name',
            'vname' => 'LBL_MOVE_TO_CENTER_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => true,
            'len' => '255',
            'id_name' => 'move_to_center_id',
            'ext2' => 'Teams',
            'module' => 'Teams',
            'studio' => 'visible',
        ),
        //Relate field with team
        'move_from_center_id' =>  array (
            'required' => false,
            'name' => 'move_from_center_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => false,
            'len' => 36,
        ),

        'move_from_center_name' =>  array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'move_from_center_name',
            'vname' => 'LBL_MOVE_FROM_CENTER_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => true,
            'len' => '255',
            'id_name' => 'move_from_center_id',
            'ext2' => 'Teams',
            'module' => 'Teams',
            'studio' => 'visible',
        ),
        //Relate field with Student
        'transfer_to_student_id' =>  array (
            'required' => false,
            'name' => 'transfer_to_student_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => false,
            'len' => 36,
        ),

        'transfer_to_student_name' =>  array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'transfer_to_student_name',
            'vname' => 'LBL_TRANSFER_TO_STUDENT_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => true,
            'len' => '255',
            'id_name' => 'transfer_to_student_id',
            'ext2' => 'Contacts',
            'module' => 'Contacts',
            'studio' => 'visible',
        ),
        //Add Field Attachment
        'filename' =>
        array (
            'name' => 'filename',
            'vname' => 'LBL_FILENAME',
            'type' => 'varchar',
            'required'=>true,
            'importable' => 'true',
            'len' => '255',
            'studio' => 'false',
        ),
        'file_ext' =>
        array (
            'name' => 'file_ext',
            'vname' => 'LBL_FILE_EXTENSION',
            'type' => 'varchar',
            'len' => 100,
        ),
        'file_mime_type' =>
        array (
            'name' => 'file_mime_type',
            'vname' => 'LBL_MIME',
            'type' => 'varchar',
            'len' => '100',
        ),
        'uploadfile' =>
        array (
            'name'=>'uploadfile',
            'vname' => 'LBL_FILE_UPLOAD',
            'type' => 'file',
            'source' => 'non-db',
        ),
        //Custom Relationship JUNIOR. Payment - Carryforward  By Lap Nguyen
        'c_carryforward'=>array(
            'name' => 'c_carryforward',
            'type' => 'link',
            'relationship' => 'j_payment_carryforward',
            'module' => 'C_Carryforward',
            'bean_name' => 'C_Carryforward',
            'source' => 'non-db',
            'vname' => 'LBL_CARRYFORWARD',
        ),
        //Custom Relationship JUNIOR. Payment - Student Situation  By Lap Nguyen
        'ju_studentsituations'=>array(
            'name' => 'ju_studentsituations',
            'type' => 'link',
            'relationship' => 'j_payment_studentsituations',
            'module' => 'J_StudentSituations',
            'bean_name' => 'J_StudentSituations',
            'source' => 'non-db',
            'vname' => 'LBL_STUDENT_SITUATION',
        ),
        //Custom Relationship JUNIOR. Payment - Student Situation  By Lap Nguyen
        'ju_sponsor'=>array(
            'name' => 'ju_sponsor',
            'type' => 'link',
            'relationship' => 'j_payment_j_sponsor',
            'module' => 'J_Sponsor',
            'bean_name' => 'J_Sponsor',
            'source' => 'non-db',
            'vname' => 'LBL_SPONSOR_COUNT',
        ),
        //Custom Relationship JUNIOR. Payment  - StudentSituation (1-n)  By Bui Kim Tung
        // Left side
        'ju_payment_in' => array(
            'name'          => 'ju_payment_in',
            'type'          => 'link',
            'relationship'  => 'j_payment_moving_transfer',
            'module'        => 'J_Payment',
            'bean_name'     => 'J_Payment',
            'source'        => 'non-db',
            'vname'         => 'LBL_PAYMENT_IN_NAME',
        ),
        // Right side
        'payment_out_name' => array(
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'payment_out_name',
            'vname'     => 'LBL_PAYMENT_OUT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'payment_out_id',
            'join_name' => 'payment',
            'link'      => 'ju_payment_out',
            'table'     => 'j_payment',
            'isnull'    => 'true',
            'module'    => 'J_Payment',
        ),
        'payment_out_id' => array(
            'name'              => 'payment_out_id',
            'rname'             => 'id',
            'vname'             => 'LBL_PAYMENT_OUT_ID',
            'type'              => 'id',
            'table'             => 'j_payment',
            'isnull'            => 'true',
            'module'            => 'J_Payment',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),
        'enrollment_id' => array(
            'name'              => 'enrollment_id',
            'vname'             => 'Enrollment ID',
            'type'              => 'id',
        ),
        'ju_payment_out' => array(
            'name'          => 'ju_payment_out',
            'type'          => 'link',
            'relationship'  => 'j_payment_moving_transfer',
            'module'        => 'J_Payment',
            'bean_name'     => 'J_Payment',
            'source'        => 'non-db',
            'vname'         => 'LBL_PAYMENT_OUT_NAME',
        ),

        //Add Relationship Situation Delay - Payment Delay (1 - n)

        //Right Side (n)
        'delay_situation_id' => array(
            'name' => 'delay_situation_id',
            'vname' => 'LBL_DELAY_SITUATION_ID',
            'type' => 'id',
            'required'=>false,
            'reportable'=>false,
            'comment' => ''
        ),

        'delay_situation_name' => array(
            'name' => 'delay_situation_name',
            'rname' => 'name',
            'id_name' => 'delay_situation_id',
            'vname' => 'LBL_DELAY_SITUATION_NAME',
            'type' => 'relate',
            'link' => 'situation_delay_link',
            'table' => 'j_studentsituations',
            'isnull' => 'true',
            'module' => 'J_StudentSituations',
            'dbType' => 'varchar',
            'len' => 'id',
            'reportable'=>true,
            'source' => 'non-db',
        ),

        'situation_delay_link' => array(
            'name' => 'situation_delay_link',
            'type' => 'link',
            'relationship' => 'situation_delay_payment_delay',
            'link_type' => 'one',
            'side' => 'right',
            'source' => 'non-db',
            'vname' => 'LBL_DELAY_SITUATION_NAME',
        ),

        //Custom Relationship JUNIOR. Payment enrollment - Sponsor  By Nhi Vo
        'sponsor_link'=>array(
            'name' => 'sponsor_link',
            'type' => 'link',
            'relationship' => 'j_payment_c_sponsor',
            'module' => 'C_Sponsors',
            'bean_name' => 'C_Sponsors',
            'source' => 'non-db',
            'vname' => 'LBL_SPONSOR',
        ),

        //Add Relationship Payment - Payment Detail (Split Payment)
        'paymentdetail_link'=>array(
            'name' => 'paymentdetail_link',
            'type' => 'link',
            'relationship' => 'payment_paymentdetails',
            'module' => 'J_PaymentDetail',
            'bean_name' => 'J_PaymentDetail',
            'source' => 'non-db',
            'vname' => 'LBL_PAYMENT_DETAIL',
        ),
        'invoice_link'=>array(
            'name' => 'invoice_link',
            'type' => 'link',
            'relationship' => 'payment_invoices',
            'module' => 'J_Invoice',
            'bean_name' => 'J_Invoice',
            'source' => 'non-db',
            'vname' => 'LBL_INVOICE',
        ),


        //Add Relationship Payment - Loyalty
        'loyalty_link'=>array(
            'name' => 'loyalty_link',
            'type' => 'link',
            'relationship' => 'payment_loyaltys',
            'module' => 'J_Loyalty',
            'bean_name' => 'J_Loyalty',
            'source' => 'non-db',
            'vname' => 'LBL_LOYALTY',
        ),

        //Add Relationship Lead - Payment (Placement Test)
        'lead_id' => array(
            'name' => 'lead_id',
            'vname' => 'LBL_LEAD_ID',
            'type' => 'id',
            'required'=>false,
            'reportable'=>false,
            'comment' => ''
        ),

        'lead_name' => array(
            'name' => 'lead_name',
            'rname' => 'first_name',
            'id_name' => 'lead_name',
            'vname' => 'LBL_LEAD_NAME',
            'type' => 'relate',
            'link' => 'lead_link',
            'table' => 'leads',
            'isnull' => 'true',
            'module' => 'Leads',
            'dbType' => 'varchar',
            'len' => 'id',
            'reportable'=>true,
            'source' => 'non-db',
        ),
        'lead_link' => array(
            'name' => 'lead_link',
            'type' => 'link',
            'relationship' => 'lead_payments',
            'link_type' => 'one',
            'side' => 'right',
            'source' => 'non-db',
            'vname' => 'LBL_LEAD_NAME',
        ),
        //Add Relationship Account - Payment (Xuất hóa đơn Corporate)
        'account_id' => array(
            'name' => 'account_id',
            'vname' => 'LBL_ACCOUNT_ID',
            'type' => 'id',
            'required'=>false,
            'reportable'=>false,
            'comment' => ''
        ),

        'account_name' => array(
            'name' => 'account_name',
            'rname' => 'name',
            'id_name' => 'account_id',
            'vname' => 'LBL_ACCOUNT_NAME',
            'type' => 'relate',
            'link' => 'account_link',
            'table' => 'accounts',
            'isnull' => 'true',
            'module' => 'Accounts',
            'dbType' => 'varchar',
            'len' => 'id',
            'reportable'=>true,
            'source' => 'non-db',
        ),
        'account_link' => array(
            'name' => 'account_link',
            'type' => 'link',
            'relationship' => 'account_payments',
            'link_type' => 'one',
            'side' => 'right',
            'source' => 'non-db',
            'vname' => 'LBL_ACCOUNT_NAME',
        ),
        'payment_use_payment' =>
        array (
            'name' => 'payment_use_payment',
            'rname' => 'id',
            'relationship_fields'=>array(
                'j_payment_j_payment_1j_payment_ida' => 'use_payment_id',
                'amount' => 'display_used_amount',
                'hours' => 'display_used_hours'
            ),
            'vname' => 'LBL_PAYMENT_USE_PAYMENT',
            'type' => 'relate',
            'link' => 'j_payment_j_payment_1',
            'link_type' => 'relationship_info',
            'join_link_name' => 'j_payment_j_payment_1',
            'source' => 'non-db',
            'importable' => 'false',
            'duplicate_merge'=> 'disabled',
            'studio' => false,
        ),
        'display_used_amount' =>
        array(
            'massupdate' => false,
            'name' => 'display_used_amount',
            'type' => 'currency',
            'studio' => 'false',
            'source' => 'non-db',
            'vname' => 'LBL_USE_AMOUNT',
            'importable' => 'false',
        ),
        'display_used_hours' =>
        array(
            'massupdate' => false,
            'name' => 'display_used_hours',
            'type' => 'decimal',
            'studio' => 'false',
            'source' => 'non-db',
            'vname' => 'LBL_USE_HOURS',
            'importable' => 'false',
        ),
        'use_payment_id' =>
        array(
            'name' => 'payment_used_id',
            'type' => 'varchar',
            'source' => 'non-db',
            'vname' => 'LBL_ATTENDANCE_ID',
            'studio' => array('listview' => false),
        ),
        'use_type' =>
        array (
            'required' => true,
            'name' => 'use_type',
            'vname' => 'LBL_USE_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Hour',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 50,
            'size' => '20',
            'options' => 'use_type_options',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'refund_revenue' =>
        array (
            'name' => 'refund_revenue',
            'vname' => 'LBL_DROP_REVENUE',
            'type' => 'currency',
            'len' => 13,
            'precision' => 2,
        ),
        'parent_type' =>
        array (
            'required' => false,
            'name' => 'parent_type',
            'vname' => 'LBL_PARENT',
            'type' => 'enum',
            'options' => 'ptresult_student_options',
            'massupdate' => 0,
            'default' => 'Contacts',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '30',
            'size' => '20',
        ),
        'sale_type_date' =>
        array (
            'required' => true,
            'name' => 'sale_type_date',
            'vname' => 'LBL_SALE_TYPE_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'catch_limit' =>
        array (
            'name' => 'catch_limit',
            'vname' => 'LBL_CATCH_LIMIT',
            'type' => 'bool',
            'default' => '0',
        ),
        'kind_of_course' =>
        array (
            'required' => true,
            'name' => 'kind_of_course',
            'vname' => 'LBL_KIND_OF_COURSE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 50,
            'size' => '20',
            'options' => 'kind_of_course_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'kind_of_course_360' =>
        array (
            'required' => true,
            'name' => 'kind_of_course_360',
            'vname' => 'LBL_KIND_OF_COURSE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 50,
            'size' => '20',
            'options' => 'kind_of_course_360_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        // ******** TASK IMPORT ***********************
        'aims_id' =>
        array (
            'required' => false,
            'name' => 'aims_id',
            'vname' => 'LBL_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'AIMS ID Int',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'class_aims_id' =>
        array (
            'required' => true,
            'name' => 'class_aims_id',
            'vname' => 'LBL_CLASS_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'AIMS ID Int',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'student_aims_id' =>
        array (
            'required' => true,
            'name' => 'student_aims_id',
            'vname' => 'LBL_STUDENT_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'AIMS ID Int',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'class_aims_id' =>
        array (
            'required' => true,
            'name' => 'class_aims_id',
            'vname' => 'LBL_CLASS_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'AIMS ID Int',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'transfer_in_aims_id' =>
        array (
            'required' => true,
            'name' => 'transfer_in_aims_id',
            'vname' => 'LBL_TRANSFER_IN_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'AIMS ID Int',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'from_payment_aims_id' =>
        array (
            'required' => true,
            'name' => 'from_payment_aims_id',
            'vname' => 'LBL_FROM_PAYMENT_AIMS_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'From Payment AIMS ID ',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '10',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
        ),
        'serial_no' =>
        array (
            'required' => false,
            'name' => 'serial_no',
            'vname' => 'LBL_SERIAL_NO',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Serial No',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '20',
            'size' => '20',
            'source' => 'non-db',
        ),
        'invoice_number' =>
        array (
            'required' => false,
            'name' => 'invoice_number',
            'vname' => 'LBL_INVOICE_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Invoice Number',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '20',
            'size' => '20',
            'source' => 'non-db',
        ),
        'invoice_date' =>
        array (
            'required' => true,
            'name' => 'invoice_date',
            'vname' => 'LBL_INVOICE_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => true,
            'comments' => '',
            'help' => 'Payment Date',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'source' => 'non-db',
        ),
        // ******** END: TASK IMPORT ***********************

        // Relationship Payment ( 1 - n ) Delivery Revenue
        'revenue_link' =>
        array (
            'name' => 'revenue_link',
            'type' => 'link',
            'relationship' => 'ju_payment_revenue',
            'module' => 'C_DeliveryRevenue',
            'bean_name' => 'C_DeliveryRevenue',
            'source' => 'non-db',
            'vname' => 'LBL_DELIVERY_REVENUE',
        ),
        //END: Relationship Payment ( 1 - n ) Delivery Revenue


        //Add Relationship Contract - Payment
        'contract_id' => array(
            'name' => 'contract_id',
            'vname' => 'LBL_CONTRACT_ID',
            'type' => 'id',
            'required'=>false,
            'reportable'=>false,
            'comment' => ''
        ),

        'contract_name' => array(
            'name' => 'contract_name',
            'rname' => 'name',
            'id_name' => 'contract_id',
            'vname' => 'LBL_CONTRACT_NAME',
            'type' => 'relate',
            'link' => 'contract_link',
            'table' => 'contracts',
            'isnull' => 'true',
            'module' => 'Contracts',
            'dbType' => 'varchar',
            'len' => 'id',
            'reportable'=>true,
            'source' => 'non-db',
        ),

        'contract_link' => array(
            'name' => 'contract_link',
            'type' => 'link',
            'relationship' => 'contract_j_payment',
            'link_type' => 'one',
            'side' => 'right',
            'source' => 'non-db',
            'vname' => 'LBL_CONTRACT_NAME',
        ),

        'is_new_student' => array(
            'name' => 'is_new_student',
            'vname' => 'LBL_IS_NEW_STUDENT',
            'type'  => 'bool',
            'default' => '0',
        ),
    ),
    'indices' => array (
        array(
            'name' => 'aims_id',
            'type' => 'index',
            'fields'=> array('aims_id'),
        ),
    ),
    'relationships'=>array (
    //Custom Relationship JUNIOR. Payment - CarryForward  By Lap Nguyen
        'j_payment_carryforward' => array(
            'lhs_module'        => 'J_Payment',
            'lhs_table'            => 'j_payment',
            'lhs_key'            => 'id',
            'rhs_module'        => 'C_Carryforward',
            'rhs_table'            => 'c_carryforward',
            'rhs_key'            => 'payment_id',
            'relationship_type'    => 'one-to-many',
        ),
        //Custom Relationship JUNIOR. Payment - Student Situation  By Lap Nguyen
        'j_payment_studentsituations' => array(
            'lhs_module'        => 'J_Payment',
            'lhs_table'            => 'j_payment',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_StudentSituations',
            'rhs_table'            => 'j_studentsituations',
            'rhs_key'            => 'payment_id',
            'relationship_type'    => 'one-to-many',
        ),
        //Custom Relationship JUNIOR. Payment - Sponsor  By Lap Nguyen
        'j_payment_j_sponsor' => array(
            'lhs_module'        => 'J_Payment',
            'lhs_table'            => 'j_payment',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_Sponsor',
            'rhs_table'            => 'j_sponsor',
            'rhs_key'            => 'payment_id',
            'relationship_type'    => 'one-to-many',
        ),
        //Custom Relationship JUNIOR. Moving - Transfer  By Tung Bui Kim
        'j_payment_moving_transfer' => array(
            'lhs_module'        => 'J_Payment',
            'lhs_table'            => 'j_payment',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_Payment',
            'rhs_table'            => 'j_payment',
            'rhs_key'            => 'payment_out_id',
            'relationship_type'    => 'one-to-many',
        ),
        //Add Relationship Payment - Payment Detail (Split Payment)
        'payment_paymentdetails' => array(
            'lhs_module' => 'J_Payment',
            'lhs_table' => 'j_payment',
            'lhs_key' => 'id',
            'rhs_module' => 'J_PaymentDetail',
            'rhs_table' => 'j_paymentdetail',
            'rhs_key' => 'payment_id',
            'relationship_type' => 'one-to-many'
        ),
        'payment_invoices' => array(
            'lhs_module' => 'J_Payment',
            'lhs_table' => 'j_payment',
            'lhs_key' => 'id',
            'rhs_module' => 'J_Invoice',
            'rhs_table' => 'j_invoice',
            'rhs_key' => 'payment_id',
            'relationship_type' => 'one-to-many'
        ),
        //Add Relationship Payment - Loyalty
        'payment_loyaltys' => array(
            'lhs_module' => 'J_Payment',
            'lhs_table' => 'j_payment',
            'lhs_key' => 'id',
            'rhs_module' => 'J_Loyalty',
            'rhs_table' => 'j_loyalty',
            'rhs_key' => 'payment_id',
            'relationship_type' => 'one-to-many'
        ),
        //Add Relationship Payment - Revenue (
        'ju_payment_revenue' => array(
            'lhs_module'        => 'J_Payment',
            'lhs_table'            => 'j_payment',
            'lhs_key'            => 'id',
            'rhs_module'        => 'C_DeliveryRevenue',
            'rhs_table'            => 'c_deliveryrevenue',
            'rhs_key'            => 'ju_payment_id',
            'relationship_type'    => 'one-to-many',
        ),
    ),
    'optimistic_locking'=>true,
    'unified_search'=>true,
);
if (!class_exists('VardefManager')){
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('J_Payment','J_Payment', array('basic','team_security','assignable'));