/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/
({label:'',forecast_ranges_field:{},buckets_dom_field:{},category_ranges_field:{},selection:'',fieldRanges:{},disableRanges:false,initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.label=_.first(this.meta.panels).label;_.each(['forecast_ranges','buckets_dom','category_ranges'],function(item){var fields=_.first(this.meta.panels).fields;this[item+'_field']=function(fieldName,fieldMeta){return _.find(fieldMeta,function(field){return field.name==this;},fieldName);}(item,fields);},this);this.forecast_ranges_field.value=this.model.get('forecast_ranges');this.buckets_dom_field.value=this.model.get('buckets_dom');if(!_.isUndefined(options.meta.registerLabelAsBreadCrumb)&&options.meta.registerLabelAsBreadCrumb==true){this.layout.registerBreadCrumbLabel(options.meta.panels[0].label);}},_render:function(){this.disableRanges=this.context.forecasts.config.get('has_commits');this.selection=this.context.forecasts.config.get('forecast_ranges');app.view.View.prototype._render.call(this);this._addForecastRangesSelectionHandler();return this;},_addForecastRangesSelectionHandler:function(){var elements=this.$el.find(':radio[name="'+this.forecast_ranges_field.name+'"]');_.each(elements,function(el){$(el).change({view:this},this.selectionHandler);if($(el).prop('checked')){$(el).triggerHandler("change");}},this);},selectionHandler:function(event){var view=event.data.view,oldValue,bucket_dom,hideElement,showElement,ranges_options;oldValue=view.selection;view.selection=this.value;bucket_dom=view.buckets_dom_field.options[this.value];hideElement=view.$el.find('#'+oldValue+'_ranges');showElement=view.$el.find('#'+this.value+'_ranges');if(showElement.children().length==0){ranges_options=app.lang.getAppListStrings(bucket_dom);view.fieldRanges[this.value]={};showElement.append('<p>'+app.lang.get('LBL_FORECASTS_CONFIG_'+this.value.toUpperCase()+'_RANGES_DESCRIPTION','Forecasts')+'</p>');_.each(ranges_options,function(label,key){if(key!='exclude'){var rangeField,model=new Backbone.Model(),fieldSettings;model.set(key,this.view.model.get(this.ranges+'_ranges')[key]);fieldSettings={view:this.view,def:_.find(_.find(_.first(this.view.meta.panels).fields,function(field){return field.name=='category_ranges';}).ranges,function(range){return range.name==this.key},{key:key}),viewName:'edit',context:this.view.context,module:this.view.module,model:model,meta:app.metadata.getField('range')};if(this.view.disableRanges){fieldSettings.viewName='detail';fieldSettings.def.view='detail';}
rangeField=app.view.createField(fieldSettings);this.showElement.append('<b>'+label+':</b>').append(rangeField.el);rangeField.render();view.fieldRanges[this.ranges][key]=rangeField;rangeField.sliderDoneDelegate=function(ranges,key,view){return function(value){view.updateRangeSettings(ranges,key,value);};}(this.ranges,key,this.view);}},{view:view,showElement:showElement,ranges:this.value});showElement.append('<b>'+ranges_options['exclude']+':</b>').append($('<p>'+app.lang.get("LBL_FORECASTS_CONFIG_RANGES_EXCLUDE_INFO","Forecasts")+'</p>'));view.connectSliders.call(view,this.value,view.fieldRanges);}
if(hideElement){hideElement.toggleClass('hide',true);}
if(showElement){showElement.toggleClass('hide',false);}
view.model.set(this.name,this.value);view.model.set(view.buckets_dom_field.name,bucket_dom);},updateRangeSettings:function(category,range,value){var catRange=category+'_ranges',setting=this.model.get(catRange);setting[range]=value;this.model.unset(catRange,{silent:true});this.model.set(catRange,setting);},connectSliders:function(ranges,sliders){var rangeSliders=sliders[ranges];if(ranges=='show_binary'){rangeSliders.include.sliderChangeDelegate=function(value){rangeSliders.include.$el.find(rangeSliders.include.fieldTag).noUiSlider('move',{handle:'upper',to:rangeSliders.include.def.maxRange});this.view.setExcludeValueForLastSlider(value,ranges,rangeSliders.include);};}else if(ranges=='show_buckets'){rangeSliders.include.sliderChangeDelegate=function(value){rangeSliders.include.$el.find(rangeSliders.include.fieldTag).noUiSlider('move',{handle:'upper',to:rangeSliders.include.def.maxRange});rangeSliders.upside.$el.find(rangeSliders.upside.fieldTag).noUiSlider('move',{handle:'upper',to:value.min-1});if(value.min<=rangeSliders.upside.$el.find(rangeSliders.upside.fieldTag).noUiSlider('value')[0]+1){rangeSliders.upside.$el.find(rangeSliders.upside.fieldTag).noUiSlider('move',{handle:'lower',to:value.min-2});}};rangeSliders.upside.sliderChangeDelegate=function(value){rangeSliders.include.$el.find(rangeSliders.include.fieldTag).noUiSlider('move',{handle:'lower',to:value.max+1});this.view.setExcludeValueForLastSlider(value,ranges,rangeSliders.upside);};}},setExcludeValueForLastSlider:function(value,ranges,slider){var excludeRange={min:0,max:100},settingName=ranges+'_ranges',setting=this.model.get(settingName);excludeRange.max=value.min-1;excludeRange.min=slider.def.minRange;setting.exclude=excludeRange;this.model.set(settingName,setting);}})