<?php
    $dictionary["J_Partnership"]["fields"]["status"] = array ( 
        'required' => false,
        'name' => 'status',
        'vname' => 'LBL_STATUS',
        'type' => 'enum',
        'massupdate' => 0,
        'default' => 'Active',
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'calculated' => false,
        'len' => 100,
        'size' => '20',
        'options' => 'status_partnership_list',
        'studio' => 'visible',
        'dependency' => false,
    ); 
   /* $dictionary["J_Partnership"]["fields"]["discount"] = array ( 
        'required' => false,
        'name' => 'discount',
        'vname' => 'LBL_DISCOUNT',
        'type' => 'enum',
        'massupdate' => 0,
        'default' => 'Active',
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'calculated' => false,
        'len' => 100,
        'size' => '20',
        'options' => 'discount_partnership_list',
        'studio' => 'visible',
        'dependency' => false,
    ); */
     $dictionary["J_Partnership"]["fields"]["schema"] = array ( 
        'name'      => 'schema',
        'vname'     => 'LBL_SCHEMA',
        'type'      => 'text',
        'source' => 'non-db',
        'studio'    => 'visible',
    );  

